Option Strict On

' <summary>
' Row captions, section headings and the one-line descriptions of the .NET 10
' settings shell (Table_Form.ModernLayout.vb), plus the project links on the
' "About" page. See Localization.vb for the key convention.
' </summary>
Partial Public NotInheritable Class Localization

    Private Shared Sub AddSettingsHintStrings()

        ' --- headings and buttons ------------------------------------------------
        Add("Настройки", "Settings", "Налаштування", "Einstellungen", "Impostazioni", "Configuración", "Paramètres", "Configurações", "الإعدادات", "सेटिंग्स", "সেটিংস", "ترتیبات", "设置")
        Add("Открыть параметры Windows", "Open Windows settings", "Відкрити параметри Windows", "Windows-Einstellungen öffnen", "Apri le impostazioni di Windows", "Abrir la configuración de Windows", "Ouvrir les paramètres Windows", "Abrir as configurações do Windows", "فتح إعدادات Windows", "Windows सेटिंग्स खोलें", "Windows সেটিংস খুলুন", "Windows ترتیبات کھولیں", "打开 Windows 设置")
        Add("Управление SFTP", "Manage SFTP", "Керування SFTP", "SFTP verwalten", "Gestisci SFTP", "Gestionar SFTP", "Gérer SFTP", "Gerenciar SFTP", "إدارة SFTP", "SFTP प्रबंधित करें", "SFTP পরিচালনা", "SFTP کا انتظام", "管理 SFTP")
        Add("Установить", "Install", "Встановити", "Installieren", "Installa", "Instalar", "Installer", "Instalar", "تثبيت", "इंस्टॉल करें", "ইনস্টল করুন", "انسٹال کریں", "安装")
        Add("Запустить", "Start", "Запустити", "Starten", "Avvia", "Iniciar", "Démarrer", "Iniciar", "تشغيل", "शुरू करें", "চালু করুন", "شروع کریں", "启动")
        Add("Загрузить", "Download", "Завантажити", "Herunterladen", "Scarica", "Descargar", "Télécharger", "Baixar", "تنزيل", "डाउनलोड करें", "ডাউনলোড করুন", "ڈاؤن لوڈ کریں", "下载")
        Add("Открыть", "Open", "Відкрити", "Öffnen", "Apri", "Abrir", "Ouvrir", "Abrir", "فتح", "खोलें", "খুলুন", "کھولیں", "打开")

        ' --- recipients overlay ---------------------------------------------------
        Add("Таблица получателей поверх изображения", "Destination table over the image", "Таблиця отримувачів поверх зображення", "Zieltabelle über dem Bild", "Tabella delle destinazioni sopra l'immagine", "Tabla de destinos sobre la imagen", "Table des destinations sur l'image", "Tabela de destinos sobre a imagem", "جدول الوجهات فوق الصورة", "छवि के ऊपर गंतव्य तालिका", "ছবির উপরে গন্তব্য টেবিল", "تصویر پر منزل ٹیبل", "图片上方的目标表格")
        Add("Вид таблицы получателей", "Destination table appearance", "Вигляд таблиці отримувачів", "Darstellung der Zieltabelle", "Aspetto della tabella delle destinazioni", "Apariencia de la tabla de destinos", "Apparence de la table des destinations", "Aparência da tabela de destinos", "مظهر جدول الوجهات", "गंतव्य तालिका का रूप", "গন্তব্য টেবিলের চেহারা", "منزل ٹیبل کی شکل", "目标表格外观")
        Add("Положение таблицы", "Table position", "Розташування таблиці", "Position der Tabelle", "Posizione della tabella", "Posición de la tabla", "Position de la table", "Posição da tabela", "موضع الجدول", "तालिका की स्थिति", "টেবিলের অবস্থান", "ٹیبل کی جگہ", "表格位置")
        Add("Ширина таблицы", "Table width", "Ширина таблиці", "Breite der Tabelle", "Larghezza della tabella", "Ancho de la tabla", "Largeur de la table", "Largura da tabela", "عرض الجدول", "तालिका की चौड़ाई", "টেবিলের প্রস্থ", "ٹیبل کی چوڑائی", "表格宽度")
        Add("Размер текста", "Text size", "Розмір тексту", "Textgröße", "Dimensione del testo", "Tamaño del texto", "Taille du texte", "Tamanho do texto", "حجم النص", "पाठ का आकार", "লেখার আকার", "متن کا سائز", "文字大小")
        Add("Непрозрачность", "Opacity", "Непрозорість", "Deckkraft", "Opacità", "Opacidad", "Opacité", "Opacidade", "العتامة", "अपारदर्शिता", "অস্বচ্ছতা", "دھندلاپن", "不透明度")
        Add("Видимые строки", "Visible rows", "Видимі рядки", "Sichtbare Zeilen", "Righe visibili", "Filas visibles", "Lignes visibles", "Linhas visíveis", "الصفوف الظاهرة", "दृश्य पंक्तियाँ", "দৃশ্যমান সারি", "نظر آنے والی قطاریں", "可见行数")

        ' --- background -----------------------------------------------------------
        Add("Фон изображения", "Image background", "Фон зображення", "Bildhintergrund", "Sfondo dell'immagine", "Fondo de la imagen", "Fond de l'image", "Fundo da imagem", "خلفية الصورة", "छवि पृष्ठभूमि", "ছবির পটভূমি", "تصویر کا پس منظر", "图片背景")
        Add("Цвет фона", "Background colour", "Колір фону", "Hintergrundfarbe", "Colore di sfondo", "Color de fondo", "Couleur de fond", "Cor de fundo", "لون الخلفية", "पृष्ठभूमि रंग", "পটভূমির রঙ", "پس منظر کا رنگ", "背景颜色")
        Add("Перспективный фон", "Perspective background", "Перспективний фон", "Perspektivischer Hintergrund", "Sfondo prospettico", "Fondo en perspectiva", "Fond en perspective", "Fundo em perspectiva", "خلفية منظورية", "परिप्रेक्ष्य पृष्ठभूमि", "পরিপ্রেক্ষিত পটভূমি", "تناظری پس منظر", "透视背景")
        Add("Динамический ореол", "Dynamic halo", "Динамічний ореол", "Dynamischer Halo", "Alone dinamico", "Halo dinámico", "Halo dynamique", "Halo dinâmico", "هالة ديناميكية", "गतिशील आभा", "গতিশীল আভা", "متحرک ہالہ", "动态光晕")
        Add("Анимация ореола", "Halo animation", "Анімація ореолу", "Halo-Animation", "Animazione dell'alone", "Animación del halo", "Animation du halo", "Animação do halo", "حركة الهالة", "आभा एनिमेशन", "আভার অ্যানিমেশন", "ہالے کی حرکت", "光晕动画")
        Add("Скорость анимации ореола", "Halo animation speed", "Швидкість анімації ореолу", "Geschwindigkeit der Halo-Animation", "Velocità dell'animazione dell'alone", "Velocidad de la animación del halo", "Vitesse de l'animation du halo", "Velocidade da animação do halo", "سرعة حركة الهالة", "आभा एनिमेशन की गति", "আভার অ্যানিমেশনের গতি", "ہالے کی حرکت کی رفتار", "光晕动画速度")

        ' --- info / controls -------------------------------------------------------
        Add("Информация и управление", "Information and controls", "Інформація та керування", "Informationen und Bedienelemente", "Informazioni e controlli", "Información y controles", "Informations et commandes", "Informações e controles", "المعلومات والتحكم", "जानकारी और नियंत्रण", "তথ্য ও নিয়ন্ত্রণ", "معلومات اور کنٹرول", "信息与控件")
        Add("Размеры изображения", "Image dimensions", "Розміри зображення", "Bildabmessungen", "Dimensioni dell'immagine", "Dimensiones de la imagen", "Dimensions de l'image", "Dimensões da imagem", "أبعاد الصورة", "छवि के आयाम", "ছবির মাত্রা", "تصویر کے ابعاد", "图片尺寸")
        Add("Размер файла", "File size", "Розмір файлу", "Dateigröße", "Dimensione del file", "Tamaño del archivo", "Taille du fichier", "Tamanho do arquivo", "حجم الملف", "फ़ाइल का आकार", "ফাইলের আকার", "فائل کا سائز", "文件大小")
        Add("Дата изменения файла", "File modification date", "Дата зміни файлу", "Änderungsdatum der Datei", "Data di modifica del file", "Fecha de modificación del archivo", "Date de modification du fichier", "Data de modificação do arquivo", "تاريخ تعديل الملف", "फ़ाइल संशोधन तिथि", "ফাইল পরিবর্তনের তারিখ", "فائل تبدیلی کی تاریخ", "文件修改日期")
        Add("Информация поверх изображения", "Information over the image", "Інформація поверх зображення", "Informationen über dem Bild", "Informazioni sopra l'immagine", "Información sobre la imagen", "Informations sur l'image", "Informações sobre a imagem", "معلومات فوق الصورة", "छवि के ऊपर जानकारी", "ছবির উপরে তথ্য", "تصویر پر معلومات", "图片上的信息")
        Add("Масштабирование колёсиком", "Zoom with the mouse wheel", "Масштабування колесом", "Zoomen mit dem Mausrad", "Zoom con la rotella", "Zoom con la rueda del ratón", "Zoom à la molette", "Zoom com a roda do mouse", "التكبير بعجلة الفأرة", "माउस व्हील से ज़ूम", "মাউস হুইলে জুম", "ماؤس وہیل سے زوم", "用滚轮缩放")
        Add("Интервал слайдшоу", "Slideshow interval", "Інтервал слайд-шоу", "Diashow-Intervall", "Intervallo della presentazione", "Intervalo del pase de diapositivas", "Intervalle du diaporama", "Intervalo da apresentação", "فاصل عرض الشرائح", "स्लाइडशो अंतराल", "স্লাইডশোর বিরতি", "سلائیڈ شو کا وقفہ", "幻灯片间隔")
        Add("Размер карточки изображения", "Image card size", "Розмір картки зображення", "Größe der Bildkarte", "Dimensione della scheda immagine", "Tamaño de la tarjeta de imagen", "Taille de la vignette", "Tamanho do cartão de imagem", "حجم بطاقة الصورة", "छवि कार्ड का आकार", "ছবির কার্ডের আকার", "تصویری کارڈ کا سائز", "图片卡片大小")
        Add("Комфорт просмотра", "Viewing comfort", "Комфорт перегляду", "Betrachtungskomfort", "Comfort di visione", "Comodidad de visualización", "Confort de visionnage", "Conforto de visualização", "راحة المشاهدة", "देखने का आराम", "দেখার আরাম", "دیکھنے کا آرام", "观看舒适度")
        Add("Масштаб нового изображения", "New image scale", "Масштаб нового зображення", "Maßstab für neues Bild", "Scala della nuova immagine", "Escala de la nueva imagen", "Échelle de la nouvelle image", "Escala da nova imagem", "مقياس الصورة الجديدة", "नई छवि का पैमाना", "নতুন ছবির স্কেল", "نئی تصویر کا پیمانہ", "新图片的缩放")
        Add("Уменьшать анимацию", "Reduce motion", "Зменшувати анімацію", "Bewegung reduzieren", "Riduci le animazioni", "Reducir el movimiento", "Réduire les animations", "Reduzir animações", "تقليل الحركة", "एनिमेशन घटाएँ", "অ্যানিমেশন কমান", "حرکت کم کریں", "减少动效")

        ' --- slideshow -------------------------------------------------------------
        Add("Поведение слайд-шоу", "Slideshow behaviour", "Поведінка слайд-шоу", "Verhalten der Diashow", "Comportamento della presentazione", "Comportamiento del pase de diapositivas", "Comportement du diaporama", "Comportamento da apresentação", "سلوك عرض الشرائح", "स्लाइडशो व्यवहार", "স্লাইডশোর আচরণ", "سلائیڈ شو کا رویہ", "幻灯片行为")
        Add("Порядок показа", "Playback order", "Порядок показу", "Wiedergabereihenfolge", "Ordine di riproduzione", "Orden de reproducción", "Ordre de lecture", "Ordem de exibição", "ترتيب العرض", "प्रदर्शन क्रम", "প্রদর্শনের ক্রম", "چلانے کی ترتیب", "播放顺序")
        Add("Останавливать при ручной навигации", "Stop on manual navigation", "Зупиняти під час ручної навігації", "Bei manueller Navigation anhalten", "Ferma con la navigazione manuale", "Detener con la navegación manual", "Arrêter lors d'une navigation manuelle", "Parar na navegação manual", "التوقف عند التنقل اليدوي", "मैनुअल नेविगेशन पर रोकें", "ম্যানুয়াল নেভিগেশনে থামান", "دستی نیویگیشن پر روکیں", "手动切换时停止")
        Add("Интерфейс во время слайд-шоу", "UI during slideshow", "Інтерфейс під час слайд-шоу", "Oberfläche während der Diashow", "Interfaccia durante la presentazione", "Interfaz durante el pase de diapositivas", "Interface pendant le diaporama", "Interface durante a apresentação", "الواجهة أثناء عرض الشرائح", "स्लाइडशो के दौरान इंटरफ़ेस", "স্লাইডশোর সময় ইন্টারফেস", "سلائیڈ شو کے دوران انٹرفیس", "幻灯片播放时的界面")

        ' --- image / video ---------------------------------------------------------
        Add("Автоповорот по EXIF", "EXIF auto-rotation", "Автоповорот за EXIF", "EXIF-Autodrehung", "Rotazione automatica EXIF", "Rotación automática EXIF", "Rotation automatique EXIF", "Rotação automática EXIF", "التدوير التلقائي حسب EXIF", "EXIF स्वतः घुमाव", "EXIF স্বয়ংক্রিয় ঘূর্ণন", "EXIF خودکار گھماؤ", "EXIF 自动旋转")
        Add("Качественное масштабирование", "High-quality scaling", "Якісне масштабування", "Hochwertige Skalierung", "Ridimensionamento di qualità", "Escalado de alta calidad", "Mise à l'échelle de qualité", "Redimensionamento de alta qualidade", "تحجيم عالي الجودة", "उच्च-गुणवत्ता स्केलिंग", "উচ্চ-মানের স্কেলিং", "اعلیٰ معیار کی اسکیلنگ", "高质量缩放")
        Add("Повторять видео", "Loop video", "Повторювати відео", "Video wiederholen", "Ripeti il video", "Repetir el vídeo", "Lire la vidéo en boucle", "Repetir o vídeo", "تكرار الفيديو", "वीडियो दोहराएँ", "ভিডিও পুনরাবৃত্তি", "ویڈیو دہرائیں", "循环播放视频")
        Add("Запускать без звука", "Start muted", "Запускати без звуку", "Stumm starten", "Avvia senza audio", "Iniciar silenciado", "Démarrer en sourdine", "Iniciar sem som", "البدء صامتًا", "बिना आवाज़ शुरू करें", "শব্দ ছাড়া চালু", "بغیر آواز شروع", "静音开始")
        Add("Громкость видео", "Video volume", "Гучність відео", "Videolautstärke", "Volume del video", "Volumen del vídeo", "Volume de la vidéo", "Volume do vídeo", "مستوى صوت الفيديو", "वीडियो ध्वनि", "ভিডিও ভলিউম", "ویڈیو کی آواز", "视频音量")
        Add("Поведение видео", "Video behaviour", "Поведінка відео", "Videoverhalten", "Comportamento del video", "Comportamiento del vídeo", "Comportement de la vidéo", "Comportamento do vídeo", "سلوك الفيديو", "वीडियो व्यवहार", "ভিডিওর আচরণ", "ویڈیو کا رویہ", "视频行为")
        Add("Запускать видео автоматически", "Autoplay video", "Запускати відео автоматично", "Video automatisch abspielen", "Riproduci il video automaticamente", "Reproducir el vídeo automáticamente", "Lire la vidéo automatiquement", "Reproduzir vídeo automaticamente", "تشغيل الفيديو تلقائيًا", "वीडियो स्वतः चलाएँ", "ভিডিও স্বয়ংক্রিয় চালু", "ویڈیو خودکار چلائیں", "自动播放视频")
        Add("Задержка скрытия панели, с", "Controls hide delay, s", "Затримка приховування панелі, с", "Verzögerung bis Bedienelemente ausblenden, s", "Ritardo di scomparsa dei controlli, s", "Retardo para ocultar los controles, s", "Délai de masquage des commandes, s", "Atraso para ocultar os controles, s", "تأخير إخفاء عناصر التحكم، ث", "नियंत्रण छिपाने की देरी, से", "নিয়ন্ত্রণ লুকানোর বিলম্ব, সে", "کنٹرول چھپانے کی تاخیر، س", "控件隐藏延迟（秒）")
        Add("Показывать панель при паузе", "Show controls while paused", "Показувати панель на паузі", "Bedienelemente bei Pause anzeigen", "Mostra i controlli in pausa", "Mostrar los controles en pausa", "Afficher les commandes en pause", "Mostrar controles quando pausado", "إظهار عناصر التحكم أثناء الإيقاف المؤقت", "रुकने पर नियंत्रण दिखाएँ", "থামানো অবস্থায় নিয়ন্ত্রণ দেখান", "وقفے کے دوران کنٹرول دکھائیں", "暂停时显示控件")
        Add("Одиночный клик по видео", "Single click on video", "Одиночний клік по відео", "Einfacher Klick auf das Video", "Clic singolo sul video", "Un solo clic en el vídeo", "Simple clic sur la vidéo", "Clique simples no vídeo", "نقرة واحدة على الفيديو", "वीडियो पर एकल क्लिक", "ভিডিওতে একক ক্লিক", "ویڈیو پر واحد کلک", "单击视频")
        Add("После окончания видео", "After video ends", "Після завершення відео", "Nach Videoende", "Al termine del video", "Al terminar el vídeo", "À la fin de la vidéo", "Ao terminar o vídeo", "بعد انتهاء الفيديو", "वीडियो समाप्त होने के बाद", "ভিডিও শেষ হওয়ার পরে", "ویڈیو ختم ہونے کے بعد", "视频结束后")
        Add("Предпочтительный язык звука", "Preferred audio language", "Бажана мова звуку", "Bevorzugte Audiosprache", "Lingua audio preferita", "Idioma de audio preferido", "Langue audio préférée", "Idioma de áudio preferido", "لغة الصوت المفضلة", "पसंदीदा ऑडियो भाषा", "পছন্দের অডিও ভাষা", "پسندیدہ آڈیو زبان", "首选音频语言")
        Add("Предпочтительный язык субтитров", "Preferred subtitle language", "Бажана мова субтитрів", "Bevorzugte Untertitelsprache", "Lingua dei sottotitoli preferita", "Idioma de subtítulos preferido", "Langue de sous-titres préférée", "Idioma de legenda preferido", "لغة الترجمة المفضلة", "पसंदीदा उपशीर्षक भाषा", "পছন্দের সাবটাইটেল ভাষা", "پسندیدہ ذیلی عنوان زبان", "首选字幕语言")

        ' --- files -----------------------------------------------------------------
        Add("Переходить к следующему файлу после копирования", "Go to the next file after copying", "Переходити до наступного файлу після копіювання", "Nach dem Kopieren zur nächsten Datei wechseln", "Passa al file successivo dopo la copia", "Ir al siguiente archivo después de copiar", "Passer au fichier suivant après la copie", "Ir para o próximo arquivo após copiar", "الانتقال إلى الملف التالي بعد النسخ", "कॉपी करने के बाद अगली फ़ाइल पर जाएँ", "কপি করার পরে পরবর্তী ফাইলে যান", "نقل کرنے کے بعد اگلی فائل پر جائیں", "复制后跳到下一个文件")
        Add("Не запрашивать подтверждение", "Do not ask for confirmation", "Не запитувати підтвердження", "Nicht nach Bestätigung fragen", "Non chiedere conferma", "No pedir confirmación", "Ne pas demander de confirmation", "Não pedir confirmação", "عدم طلب التأكيد", "पुष्टि न माँगें", "নিশ্চিতকরণ চাইবেন না", "تصدیق نہ مانگیں", "不询问确认")
        Add("Форматы изображений", "Image file types", "Формати зображень", "Bilddateitypen", "Tipi di file immagine", "Tipos de archivo de imagen", "Types de fichiers image", "Tipos de arquivo de imagem", "أنواع ملفات الصور", "छवि फ़ाइल प्रकार", "ছবির ফাইল ধরন", "تصویری فائل اقسام", "图片文件类型")
        Add("Форматы видео", "Video file types", "Формати відео", "Videodateitypen", "Tipi di file video", "Tipos de archivo de vídeo", "Types de fichiers vidéo", "Tipos de arquivo de vídeo", "أنواع ملفات الفيديو", "वीडियो फ़ाइल प्रकार", "ভিডিও ফাইল ধরন", "ویڈیو فائل اقسام", "视频文件类型")
        Add("Язык интерфейса", "Interface language", "Мова інтерфейсу", "Sprache der Oberfläche", "Lingua dell'interfaccia", "Idioma de la interfaz", "Langue de l'interface", "Idioma da interface", "لغة الواجهة", "इंटरफ़ेस भाषा", "ইন্টারফেস ভাষা", "انٹرفیس کی زبان", "界面语言")
        Add("Поведение файлов", "File behaviour", "Поведінка файлів", "Dateiverhalten", "Comportamento dei file", "Comportamiento de los archivos", "Comportement des fichiers", "Comportamento dos arquivos", "سلوك الملفات", "फ़ाइल व्यवहार", "ফাইলের আচরণ", "فائل کا رویہ", "文件行为")
        Add("Совпадение имён", "Name collision", "Збіг імен", "Namenskonflikt", "Conflitto di nomi", "Colisión de nombres", "Conflit de noms", "Conflito de nomes", "تعارض الأسماء", "नाम टकराव", "নামের সংঘর্ষ", "ناموں کا ٹکراؤ", "文件名冲突")
        Add("После копирования или перемещения", "After copying or moving", "Після копіювання або переміщення", "Nach dem Kopieren oder Verschieben", "Dopo la copia o lo spostamento", "Después de copiar o mover", "Après copie ou déplacement", "Após copiar ou mover", "بعد النسخ أو النقل", "कॉपी या स्थानांतरण के बाद", "কপি বা সরানোর পরে", "نقل یا منتقلی کے بعد", "复制或移动之后")
        Add("Просматривать вложенные папки", "Include subfolders", "Переглядати вкладені теки", "Unterordner einbeziehen", "Includi le sottocartelle", "Incluir subcarpetas", "Inclure les sous-dossiers", "Incluir subpastas", "تضمين المجلدات الفرعية", "उप-फ़ोल्डर शामिल करें", "সাব-ফোল্ডার অন্তর্ভুক্ত", "ذیلی فولڈرز شامل کریں", "包含子文件夹")
        Add("Типы файлов", "File types", "Типи файлів", "Dateitypen", "Tipi di file", "Tipos de archivo", "Types de fichiers", "Tipos de arquivo", "أنواع الملفات", "फ़ाइल प्रकार", "ফাইলের ধরন", "فائل اقسام", "文件类型")
        Add("Размер истории файлов", "Recent-files limit", "Розмір історії файлів", "Grenze für zuletzt verwendete Dateien", "Limite dei file recenti", "Límite de archivos recientes", "Limite des fichiers récents", "Limite de arquivos recentes", "حد الملفات الحديثة", "हाल की फ़ाइलों की सीमा", "সাম্প্রতিক ফাইলের সীমা", "حالیہ فائلوں کی حد", "最近文件数量上限")
        Add("Размер истории папок", "Recent-folders limit", "Розмір історії тек", "Grenze für zuletzt verwendete Ordner", "Limite delle cartelle recenti", "Límite de carpetas recientes", "Limite des dossiers récents", "Limite de pastas recentes", "حد المجلدات الحديثة", "हाल के फ़ोल्डरों की सीमा", "সাম্প্রতিক ফোল্ডারের সীমা", "حالیہ فولڈرز کی حد", "最近文件夹数量上限")
        Add("При запуске открывать", "Open at startup", "Під час запуску відкривати", "Beim Start öffnen", "All'avvio apri", "Abrir al iniciar", "Ouvrir au démarrage", "Abrir ao iniciar", "الفتح عند البدء", "शुरू होने पर खोलें", "চালু হওয়ার সময় খুলুন", "شروع پر کھولیں", "启动时打开")

        ' --- OCR / translation ------------------------------------------------------
        Add("Включить OCR", "Enable OCR", "Увімкнути OCR", "OCR aktivieren", "Attiva OCR", "Activar OCR", "Activer l'OCR", "Ativar OCR", "تفعيل OCR", "OCR चालू करें", "OCR চালু করুন", "OCR فعال کریں", "启用 OCR")
        Add("Запускать автоматически", "Run automatically", "Запускати автоматично", "Automatisch ausführen", "Esegui automaticamente", "Ejecutar automáticamente", "Exécuter automatiquement", "Executar automaticamente", "التشغيل تلقائيًا", "स्वतः चलाएँ", "স্বয়ংক্রিয়ভাবে চালান", "خودکار چلائیں", "自动运行")
        AddC("settings", "Перевод", "Translation", "Переклад", "Übersetzung", "Traduzione", "Traducción", "Traduction", "Tradução", "الترجمة", "अनुवाद", "অনুবাদ", "ترجمہ", "翻译")
        Add("Сервис перевода", "Translation provider", "Сервіс перекладу", "Übersetzungsdienst", "Servizio di traduzione", "Servicio de traducción", "Service de traduction", "Serviço de tradução", "خدمة الترجمة", "अनुवाद सेवा", "অনুবাদ সেবা", "ترجمے کی سروس", "翻译服务")
        Add("Адрес сервиса", "Service address", "Адреса сервісу", "Dienstadresse", "Indirizzo del servizio", "Dirección del servicio", "Adresse du service", "Endereço do serviço", "عنوان الخدمة", "सेवा का पता", "সেবার ঠিকানা", "سروس کا پتہ", "服务地址")
        Add("Локальный сервер Ollama", "Local Ollama server", "Локальний сервер Ollama", "Lokaler Ollama-Server", "Server Ollama locale", "Servidor Ollama local", "Serveur Ollama local", "Servidor Ollama local", "خادم Ollama المحلي", "स्थानीय Ollama सर्वर", "স্থানীয় Ollama সার্ভার", "مقامی Ollama سرور", "本地 Ollama 服务器")
        Add("Модель перевода", "Translation model", "Модель перекладу", "Übersetzungsmodell", "Modello di traduzione", "Modelo de traducción", "Modèle de traduction", "Modelo de tradução", "نموذج الترجمة", "अनुवाद मॉडल", "অনুবাদ মডেল", "ترجمے کا ماڈل", "翻译模型")
        Add("API-ключ", "API key", "API-ключ", "API-Schlüssel", "Chiave API", "Clave de API", "Clé d'API", "Chave de API", "مفتاح API", "API कुंजी", "API কী", "API کلید", "API 密钥")
        Add("Язык перевода", "Translation language", "Мова перекладу", "Zielsprache", "Lingua di traduzione", "Idioma de traducción", "Langue de traduction", "Idioma da tradução", "لغة الترجمة", "अनुवाद की भाषा", "অনুবাদের ভাষা", "ترجمے کی زبان", "翻译语言")
        Add("Распознавание текста", "Text recognition", "Розпізнавання тексту", "Texterkennung", "Riconoscimento del testo", "Reconocimiento de texto", "Reconnaissance de texte", "Reconhecimento de texto", "التعرف على النص", "पाठ पहचान", "লেখা শনাক্তকরণ", "متن کی شناخت", "文字识别")
        Add("Язык исходного текста", "Source text language", "Мова початкового тексту", "Sprache des Quelltexts", "Lingua del testo originale", "Idioma del texto original", "Langue du texte source", "Idioma do texto original", "لغة النص المصدر", "स्रोत पाठ की भाषा", "মূল লেখার ভাষা", "ماخذ متن کی زبان", "源文本语言")
        Add("Качество распознавания", "Recognition quality", "Якість розпізнавання", "Erkennungsqualität", "Qualità del riconoscimento", "Calidad del reconocimiento", "Qualité de reconnaissance", "Qualidade do reconhecimento", "جودة التعرف", "पहचान की गुणवत्ता", "শনাক্তকরণের মান", "شناخت کا معیار", "识别质量")
        Add("Режим OCR", "OCR mode", "Режим OCR", "OCR-Modus", "Modalità OCR", "Modo de OCR", "Mode OCR", "Modo de OCR", "وضع OCR", "OCR मोड", "OCR মোড", "OCR موڈ", "OCR 模式")
        Add("Языковые данные", "Language data", "Мовні дані", "Sprachdaten", "Dati linguistici", "Datos de idioma", "Données linguistiques", "Dados de idioma", "بيانات اللغة", "भाषा डेटा", "ভাষার ডেটা", "زبان کا ڈیٹا", "语言数据")
        Add("Панель перевода", "Translation panel", "Панель перекладу", "Übersetzungsbereich", "Pannello di traduzione", "Panel de traducción", "Panneau de traduction", "Painel de tradução", "لوحة الترجمة", "अनुवाद पैनल", "অনুবাদ প্যানেল", "ترجمے کا پینل", "翻译面板")
        Add("Непрозрачность панели", "Panel opacity", "Непрозорість панелі", "Deckkraft des Bereichs", "Opacità del pannello", "Opacidad del panel", "Opacité du panneau", "Opacidade do painel", "عتامة اللوحة", "पैनल की अपारदर्शिता", "প্যানেলের অস্বচ্ছতা", "پینل کا دھندلاپن", "面板不透明度")
        Add("Показывать панель перевода", "Show translation overlay", "Показувати панель перекладу", "Übersetzungsüberlagerung anzeigen", "Mostra la sovrapposizione di traduzione", "Mostrar la superposición de traducción", "Afficher la surimpression de traduction", "Mostrar a sobreposição de tradução", "إظهار طبقة الترجمة", "अनुवाद ओवरले दिखाएँ", "অনুবাদ ওভারলে দেখান", "ترجمے کی تہہ دکھائیں", "显示翻译浮层")
        Add("Кэшировать результаты на диске", "Cache results on disk", "Кешувати результати на диску", "Ergebnisse auf der Festplatte zwischenspeichern", "Memorizza i risultati su disco", "Almacenar los resultados en disco", "Mettre les résultats en cache sur le disque", "Armazenar resultados em disco", "تخزين النتائج على القرص", "परिणाम डिस्क पर कैश करें", "ফলাফল ডিস্কে ক্যাশ করুন", "نتائج ڈسک پر محفوظ کریں", "将结果缓存到磁盘")
        Add("Максимальный размер OCR-кэша, МБ", "Maximum OCR cache size, MB", "Максимальний розмір OCR-кешу, МБ", "Maximale OCR-Cachegröße, MB", "Dimensione massima della cache OCR, MB", "Tamaño máximo de la caché de OCR, MB", "Taille maximale du cache OCR, Mo", "Tamanho máximo do cache de OCR, MB", "الحد الأقصى لحجم ذاكرة OCR، ميغابايت", "अधिकतम OCR कैश आकार, MB", "সর্বোচ্চ OCR ক্যাশ আকার, MB", "زیادہ سے زیادہ OCR کیش سائز، MB", "OCR 缓存最大容量（MB）")

        ' --- sharing / about ---------------------------------------------------------
        Add("Доступ к медиатеке с телефона", "Access your media library from a phone", "Доступ до медіатеки з телефона", "Zugriff auf Ihre Mediathek vom Telefon", "Accedi alla libreria multimediale dal telefono", "Acceda a su biblioteca multimedia desde el teléfono", "Accédez à votre médiathèque depuis un téléphone", "Acesse sua biblioteca de mídia pelo celular", "الوصول إلى مكتبة الوسائط من الهاتف", "फ़ोन से अपनी मीडिया लाइब्रेरी तक पहुँचें", "ফোন থেকে আপনার মিডিয়া লাইব্রেরিতে প্রবেশ", "فون سے اپنی میڈیا لائبریری تک رسائی", "从手机访问你的媒体库")
        Add("Публикация папок по SFTP", "Publish folders over SFTP", "Публікація тек через SFTP", "Ordner über SFTP veröffentlichen", "Pubblica cartelle via SFTP", "Publicar carpetas por SFTP", "Publier des dossiers via SFTP", "Publicar pastas por SFTP", "نشر المجلدات عبر SFTP", "SFTP से फ़ोल्डर प्रकाशित करें", "SFTP-এ ফোল্ডার প্রকাশ", "SFTP کے ذریعے فولڈرز شائع کریں", "通过 SFTP 发布文件夹")
        Add("Инструкция по подключению", "Connection guide", "Інструкція з підключення", "Verbindungsanleitung", "Guida alla connessione", "Guía de conexión", "Guide de connexion", "Guia de conexão", "دليل الاتصال", "कनेक्शन गाइड", "সংযোগ নির্দেশিকা", "کنکشن گائیڈ", "连接指南")
        Add("Приложение для Android", "Android application", "Застосунок для Android", "Android-Anwendung", "Applicazione Android", "Aplicación para Android", "Application Android", "Aplicativo para Android", "تطبيق أندرويد", "Android ऐप्लिकेशन", "Android অ্যাপ্লিকেশন", "Android ایپلیکیشن", "Android 应用")
        Add("Сайт Doc HTML Translate", "Doc HTML Translate website", "Сайт Doc HTML Translate", "Website von Doc HTML Translate", "Sito di Doc HTML Translate", "Sitio de Doc HTML Translate", "Site de Doc HTML Translate", "Site do Doc HTML Translate", "موقع Doc HTML Translate", "Doc HTML Translate वेबसाइट", "Doc HTML Translate ওয়েবসাইট", "Doc HTML Translate ویب سائٹ", "Doc HTML Translate 网站")
        Add("Сайт проекта", "Project website", "Сайт проєкту", "Projekt-Website", "Sito del progetto", "Sitio del proyecto", "Site du projet", "Site do projeto", "موقع المشروع", "प्रोजेक्ट वेबसाइट", "প্রকল্পের ওয়েবসাইট", "پروجیکٹ ویب سائٹ", "项目网站")
        Add("Новые версии", "Releases", "Нові версії", "Veröffentlichungen", "Versioni", "Versiones", "Versions", "Versões", "الإصدارات", "रिलीज़", "রিলিজ", "ریلیزز", "版本发布")
        Add("Политика конфиденциальности", "Privacy policy", "Політика конфіденційності", "Datenschutzerklärung", "Informativa sulla privacy", "Política de privacidad", "Politique de confidentialité", "Política de privacidade", "سياسة الخصوصية", "गोपनीयता नीति", "গোপনীয়তা নীতি", "رازداری کی پالیسی", "隐私政策")
        Add("Связаться с автором", "Contact the author", "Зв'язатися з автором", "Den Autor kontaktieren", "Contatta l'autore", "Contactar con el autor", "Contacter l'auteur", "Contatar o autor", "التواصل مع المؤلف", "लेखक से संपर्क करें", "লেখকের সাথে যোগাযোগ", "مصنف سے رابطہ کریں", "联系作者")

        AddSettingsDescriptionStrings()
        Add("Действует со следующего запуска. Настройки и позицию окна хранит первое окно. Помните: выделив в проводнике десять файлов, вы получите десять окон. По умолчанию выключено.",
            "Takes effect for subsequent launches. The first window keeps settings and its position. Remember: selecting ten files in Explorer opens ten windows. Off by default.", "Діє для наступних запусків. Налаштування та позицію вікна зберігає перше вікно. Пам'ятайте: вибравши у провіднику десять файлів, ви отримаєте десять вікон. Типово вимкнено.", "Gilt für spätere Starts. Das erste Fenster speichert Einstellungen und seine Position. Denken Sie daran: Zehn Dateien im Explorer bedeuten zehn Fenster. Standardmäßig aus.", "Ha effetto dagli avvii successivi. La prima finestra conserva impostazioni e posizione. Ricorda: selezionare dieci file in Esplora file apre dieci finestre. Disattivato per impostazione predefinita.", "Se aplica a los siguientes inicios. La primera ventana guarda la configuración y su posición. Recuerde: seleccionar diez archivos en el Explorador abre diez ventanas. Desactivado de forma predeterminada.", "S'applique aux lancements suivants. La première fenêtre conserve les réglages et sa position. Sélectionner dix fichiers dans l'Explorateur ouvre dix fenêtres. Désactivé par défaut.", "Vale para as próximas inicializações. A primeira janela guarda as configurações e sua posição. Selecionar dez arquivos no Explorador abre dez janelas. Desativado por padrão.", "يسري على عمليات التشغيل التالية. تحتفظ النافذة الأولى بالإعدادات وموضعها. تذكّر: تحديد عشرة ملفات في المستكشف يفتح عشر نوافذ. معطّل افتراضيًا.", "अगले लॉन्च से लागू होता है। पहली विंडो सेटिंग और अपनी स्थिति रखती है। याद रखें: Explorer में दस फ़ाइलें चुनने पर दस विंडो खुलेंगी। डिफ़ॉल्ट रूप से बंद है।", "পরের চালু থেকে কার্যকর হবে। প্রথম উইন্ডো সেটিংস ও অবস্থান রাখে। মনে রাখুন: Explorer-এ দশটি ফাইল বাছলে দশটি উইন্ডো খুলবে। ডিফল্টে বন্ধ।", "اگلی لانچ سے نافذ ہوتا ہے۔ پہلی ونڈو ترتیبات اور اپنی جگہ محفوظ رکھتی ہے۔ یاد رکھیں: Explorer میں دس فائلیں منتخب کرنے سے دس ونڈوز کھلیں گی۔ بطور ڈیفالٹ بند ہے۔", "从下次启动起生效。第一个窗口保存设置和位置。请注意：在资源管理器中选择十个文件会打开十个窗口。默认关闭。")
    End Sub

End Class
