Option Strict On

' <summary>
' The "send the logs to the author" flow on the About tab
' (SPECIFICATION_SEND_LOGS_TO_AUTHOR.md): the settings row, the consent dialog and
' the mail template the user fills in.
'
' The code behind these strings is modern-only, but the table is not seam-guarded:
' registering a few unused keys in the x86 build costs nothing, while a seam here
' would be one more place for the two builds to disagree.
' </summary>
Partial Public NotInheritable Class Localization

    Private Shared Sub AddSupportStrings()

        ' --- the settings row --------------------------------------------------------
        Add("Отправить логи автору", "Send the logs to the author", "Надіслати журнали автору", "Protokolle an den Autor senden", "Invia i log all'autore", "Enviar los registros al autor", "Envoyer les journaux à l'auteur", "Enviar os registros ao autor", "إرسال السجلات إلى المؤلف", "लॉग लेखक को भेजें", "লগ লেখকের কাছে পাঠান", "لاگز مصنف کو بھیجیں", "把日志发送给作者")
        Add("Собрать и отправить", "Collect and send", "Зібрати та надіслати", "Sammeln und senden", "Raccogli e invia", "Recopilar y enviar", "Collecter et envoyer", "Coletar e enviar", "اجمع وأرسل", "एकत्र करें और भेजें", "সংগ্রহ করে পাঠান", "جمع کریں اور بھیجیں", "收集并发送")
        Add("Соберёт журналы работы программы в архив и создаст письмо автору. Ничего не отправляется без вашего подтверждения.", "Packs the program logs into an archive and prepares a mail to the author. Nothing is sent without your confirmation.", "Збере журнали роботи програми в архів і створить лист автору. Нічого не надсилається без вашого підтвердження.", "Packt die Programmprotokolle in ein Archiv und bereitet eine E-Mail an den Autor vor. Ohne Ihre Bestätigung wird nichts gesendet.", "Raccoglie i log del programma in un archivio e prepara un messaggio per l'autore. Nulla viene inviato senza la tua conferma.", "Empaqueta los registros del programa en un archivo y prepara un correo al autor. No se envía nada sin su confirmación.", "Regroupe les journaux du programme dans une archive et prépare un courriel à l'auteur. Rien n'est envoyé sans votre confirmation.", "Reúne os registros do programa em um arquivo e prepara um e-mail ao autor. Nada é enviado sem a sua confirmação.", "يجمع سجلات البرنامج في أرشيف ويهيّئ رسالة إلى المؤلف. لا يُرسل شيء دون تأكيدك.", "प्रोग्राम के लॉग को एक संग्रह में पैक करता है और लेखक को पत्र तैयार करता है। आपकी पुष्टि के बिना कुछ नहीं भेजा जाता।", "প্রোগ্রামের লগ একটি আর্কাইভে গুছিয়ে লেখকের জন্য চিঠি তৈরি করে। আপনার নিশ্চিতকরণ ছাড়া কিছুই পাঠানো হয় না।", "پروگرام کے لاگز کو ایک آرکائیو میں جمع کر کے مصنف کے لیے خط تیار کرتا ہے۔ آپ کی تصدیق کے بغیر کچھ نہیں بھیجا جاتا۔", "把程序日志打包成压缩包，并为作者准备一封邮件。未经你确认不会发送任何内容。")

        ' --- the consent dialog ------------------------------------------------------
        Add("Готов архив {0} ({1}).", "Archive {0} is ready ({1}).", "Готовий архів {0} ({1}).", "Archiv {0} ist fertig ({1}).", "L'archivio {0} è pronto ({1}).", "El archivo {0} está listo ({1}).", "L'archive {0} est prête ({1}).", "O arquivo {0} está pronto ({1}).", "الأرشيف {0} جاهز ({1}).", "संग्रह {0} तैयार है ({1})।", "আর্কাইভ {0} প্রস্তুত ({1})।", "آرکائیو {0} تیار ہے ({1})۔", "压缩包 {0} 已就绪（{1}）。")
        Add("В журнале есть пути и имена файлов, которые вы открывали, и названия ваших каталогов. Откройте архив и посмотрите, что уходит, если это важно.", "The log holds the paths and names of the files you opened and the names of your folders. Open the archive and see what is leaving, if that matters to you.", "У журналі є шляхи та імена файлів, які ви відкривали, і назви ваших тек. Відкрийте архів і подивіться, що йде, якщо це важливо.", "Das Protokoll enthält die Pfade und Namen der von Ihnen geöffneten Dateien sowie die Namen Ihrer Ordner. Öffnen Sie das Archiv und sehen Sie nach, was hinausgeht, falls das wichtig ist.", "Il log contiene i percorsi e i nomi dei file che hai aperto e i nomi delle tue cartelle. Apri l'archivio e guarda cosa parte, se per te è importante.", "El registro contiene las rutas y los nombres de los archivos que abrió y los nombres de sus carpetas. Abra el archivo y vea qué se envía, si le importa.", "Le journal contient les chemins et les noms des fichiers que vous avez ouverts ainsi que les noms de vos dossiers. Ouvrez l'archive et regardez ce qui part, si cela compte pour vous.", "O registro contém os caminhos e os nomes dos arquivos que você abriu e os nomes das suas pastas. Abra o arquivo e veja o que está saindo, se isso importa para você.", "يحتوي السجل على مسارات وأسماء الملفات التي فتحتها وأسماء مجلداتك. افتح الأرشيف وانظر ما الذي سيُرسل إن كان ذلك يهمك.", "लॉग में उन फ़ाइलों के पथ और नाम हैं जिन्हें आपने खोला, और आपके फ़ोल्डरों के नाम भी। यदि यह मायने रखता है तो संग्रह खोलकर देखें कि क्या जा रहा है।", "লগে আপনি যেসব ফাইল খুলেছেন তাদের পথ ও নাম এবং আপনার ফোল্ডারের নাম আছে। গুরুত্বপূর্ণ মনে হলে আর্কাইভ খুলে দেখুন কী পাঠানো হচ্ছে।", "لاگ میں ان فائلوں کے راستے اور نام ہیں جو آپ نے کھولیں، اور آپ کے فولڈرز کے نام بھی۔ اگر یہ اہم ہے تو آرکائیو کھول کر دیکھیں کہ کیا جا رہا ہے۔", "日志中包含你打开过的文件路径和名称，以及你的文件夹名称。如果在意，请打开压缩包看看要发送的内容。")
        Add("Открыть архив", "Open the archive", "Відкрити архів", "Archiv öffnen", "Apri l'archivio", "Abrir el archivo", "Ouvrir l'archive", "Abrir o arquivo", "فتح الأرشيف", "संग्रह खोलें", "আর্কাইভ খুলুন", "آرکائیو کھولیں", "打开压缩包")
        Add("Отправить", "Send", "Надіслати", "Senden", "Invia", "Enviar", "Envoyer", "Enviar", "إرسال", "भेजें", "পাঠান", "بھیجیں", "发送")
        Add("Отмена", "Cancel", "Скасувати", "Abbrechen", "Annulla", "Cancelar", "Annuler", "Cancelar", "إلغاء", "रद्द करें", "বাতিল", "منسوخ کریں", "取消")
        Add("Архив получился больше {0} МБ - такое письмо почта не пропустит. Откройте архив и пришлите только нужное.", "The archive is larger than {0} MB - mail servers will not pass such a letter. Open it and send only what is needed.", "Архів вийшов більший за {0} МБ - такий лист пошта не пропустить. Відкрийте архів і надішліть лише потрібне.", "Das Archiv ist größer als {0} MB - eine solche Mail lässt der Server nicht durch. Öffnen Sie es und senden Sie nur das Nötige.", "L'archivio supera {0} MB - una mail del genere non passa. Aprilo e invia solo ciò che serve.", "El archivo supera los {0} MB: el correo no dejará pasar un mensaje así. Ábralo y envíe solo lo necesario.", "L'archive dépasse {0} Mo - un tel courriel ne passera pas. Ouvrez-la et n'envoyez que le nécessaire.", "O arquivo passou de {0} MB - um e-mail assim não passa. Abra-o e envie apenas o necessário.", "حجم الأرشيف أكبر من {0} ميغابايت - لن يمرّ بريد بهذا الحجم. افتحه وأرسل ما يلزم فقط.", "संग्रह {0} MB से बड़ा है - ऐसा पत्र मेल सर्वर पास नहीं करेगा। इसे खोलें और केवल आवश्यक भेजें।", "আর্কাইভ {0} MB-এর চেয়ে বড় - এমন চিঠি মেল সার্ভার পাঠাবে না। এটি খুলে শুধু প্রয়োজনীয় অংশ পাঠান।", "آرکائیو {0} MB سے بڑا ہے - ایسا خط میل سرور نہیں بھیجے گا۔ اسے کھولیں اور صرف ضروری چیز بھیجیں۔", "压缩包超过 {0} MB，这样的邮件无法发送。请打开它，只发送需要的部分。")
        Add("Не удалось собрать архив: {0}", "The archive could not be built: {0}", "Не вдалося зібрати архів: {0}", "Das Archiv konnte nicht erstellt werden: {0}", "Impossibile creare l'archivio: {0}", "No se pudo crear el archivo: {0}", "Impossible de créer l'archive : {0}", "Não foi possível criar o arquivo: {0}", "تعذّر إنشاء الأرشيف: {0}", "संग्रह नहीं बनाया जा सका: {0}", "আর্কাইভ তৈরি করা যায়নি: {0}", "آرکائیو نہیں بنایا جا سکا: {0}", "无法创建压缩包：{0}")
        Add("Почтовый клиент с вложением открыть не удалось. Архив скопирован в буфер обмена и показан в папке - вложите его в письмо вручную.", "A mail client with the attachment could not be opened. The archive is on the clipboard and shown in its folder - attach it to the letter by hand.", "Не вдалося відкрити поштовий клієнт із вкладенням. Архів скопійовано в буфер обміну та показано в теці - долучіть його до листа вручну.", "Ein Mailprogramm mit dem Anhang konnte nicht geöffnet werden. Das Archiv liegt in der Zwischenablage und wird im Ordner angezeigt - hängen Sie es von Hand an.", "Non è stato possibile aprire un client di posta con l'allegato. L'archivio è negli appunti ed è mostrato nella cartella - allegalo a mano.", "No se pudo abrir un cliente de correo con el adjunto. El archivo está en el portapapeles y se muestra en su carpeta: adjúntelo a mano.", "Impossible d'ouvrir un client de messagerie avec la pièce jointe. L'archive est dans le presse-papiers et affichée dans son dossier - joignez-la à la main.", "Não foi possível abrir um cliente de e-mail com o anexo. O arquivo está na área de transferência e é mostrado na pasta - anexe-o manualmente.", "تعذّر فتح برنامج بريد مع المرفق. تم نسخ الأرشيف إلى الحافظة وعرضه في مجلده - أرفقه بالرسالة يدويًا.", "अनुलग्नक के साथ मेल क्लाइंट नहीं खुल सका। संग्रह क्लिपबोर्ड में है और उसके फ़ोल्डर में दिखाया गया है - उसे पत्र में हाथ से संलग्न करें।", "সংযুক্তিসহ মেল ক্লায়েন্ট খোলা যায়নি। আর্কাইভ ক্লিপবোর্ডে নেওয়া হয়েছে ও ফোল্ডারে দেখানো হয়েছে - চিঠিতে নিজে যুক্ত করুন।", "منسلکہ کے ساتھ میل کلائنٹ نہیں کھل سکا۔ آرکائیو کلپ بورڈ میں ہے اور فولڈر میں دکھایا گیا ہے - اسے خط میں خود منسلک کریں۔", "无法打开带附件的邮件客户端。压缩包已复制到剪贴板并在文件夹中显示，请手动添加为附件。")

        ' --- the mail template the user fills in -------------------------------------
        Add("Что произошло:", "What happened:", "Що сталося:", "Was ist passiert:", "Cosa è successo:", "Qué ocurrió:", "Ce qui s'est passé :", "O que aconteceu:", "ما الذي حدث:", "क्या हुआ:", "কী ঘটেছে:", "کیا ہوا:", "发生了什么：")
        Add("Что ожидалось:", "What was expected:", "Що очікувалося:", "Was erwartet wurde:", "Cosa ci si aspettava:", "Qué se esperaba:", "Ce qui était attendu :", "O que era esperado:", "ما كان متوقعًا:", "क्या अपेक्षित था:", "কী প্রত্যাশিত ছিল:", "کیا متوقع تھا:", "期望的结果：")
        Add("Шаги для повторения:", "Steps to reproduce:", "Кроки для відтворення:", "Schritte zum Reproduzieren:", "Passi per riprodurre:", "Pasos para reproducir:", "Étapes pour reproduire :", "Passos para reproduzir:", "خطوات إعادة الإنتاج:", "दोहराने के चरण:", "পুনরাবৃত্তির ধাপ:", "دہرانے کے مراحل:", "复现步骤：")

    End Sub

End Class
