Option Strict On

' <summary>
' Strings of the settings window: the legacy tooltips of Table_Form and the row
' and section captions of the .NET 10 shell (Table_Form.ModernLayout.vb).
' Row descriptions live in Localization.SettingsHints.vb.
' </summary>
Partial Public NotInheritable Class Localization

    Private Shared Sub AddSettingsStrings()

        ' --- Table_Form.vb: control tooltips ------------------------------------
        Add("Если отмечено, файлы копируются, а не перемещаются - оригиналы никуда не денутся, что бы вы ни нажали дальше.",
            "If checked, files are copied instead of moved - the originals survive whatever you press next.",
            "Якщо позначено, файли копіюються, а не переміщуються - оригінали залишаться, що б ви не натиснули далі.",
            "Wenn aktiviert, werden Dateien kopiert statt verschoben - die Originale überleben, was Sie als Nächstes drücken.",
            "Se selezionato, i file vengono copiati invece che spostati: gli originali sopravvivono a qualunque tasto premerai.",
            "Si está marcado, los archivos se copian en vez de moverse: los originales sobreviven a lo que pulse después.",
            "Si coché, les fichiers sont copiés au lieu d'être déplacés - les originaux survivent à ce que vous ferez ensuite.",
            "Se marcado, os arquivos são copiados em vez de movidos - os originais sobrevivem ao que você apertar depois.",
            "عند التحديد، تُنسخ الملفات بدل نقلها - تبقى الأصول مهما ضغطت بعد ذلك.",
            "चुनने पर फ़ाइलें स्थानांतरित नहीं, कॉपी होती हैं - मूल फ़ाइलें बची रहती हैं।",
            "নির্বাচিত হলে ফাইল সরানোর বদলে কপি হয় - মূল ফাইল থেকে যায়।",
            "منتخب ہونے پر فائلیں منتقل نہیں، نقل ہوتی ہیں - اصل فائلیں محفوظ رہتی ہیں۔",
            "勾选后文件将被复制而非移动 - 无论你接下来按什么，原件都还在。")
        ' Mainline only: the checkbox that took the place of the global copy mode.
        Add("Если отмечено, после копирования программа сразу показывает следующий файл. Если снять галочку, после копирования остаётся текущий файл. По умолчанию включено.",
            "If checked, the app shows the next file right after a copy. If unchecked, the current file stays on screen after copying. On by default.",
            "Якщо позначено, після копіювання програма одразу показує наступний файл. Якщо зняти позначку, після копіювання залишається поточний файл. Типово увімкнено.",
            "Wenn aktiviert, zeigt das Programm nach dem Kopieren sofort die nächste Datei. Ohne Häkchen bleibt die aktuelle Datei stehen. Standardmäßig aktiv.",
            "Se selezionato, dopo la copia il programma mostra subito il file successivo. Senza spunta resta il file attuale. Attivo per impostazione predefinita.",
            "Si está marcado, tras la copia el programa muestra en seguida el siguiente archivo. Sin la marca, permanece el archivo actual. Activado de forma predeterminada.",
            "Si coché, le programme affiche le fichier suivant juste après la copie. Sinon, le fichier actuel reste à l'écran. Activé par défaut.",
            "Se marcado, após a cópia o programa mostra logo o próximo arquivo. Sem a marca, o arquivo atual permanece. Ativado por padrão.",
            "عند التحديد يعرض البرنامج الملف التالي مباشرة بعد النسخ. وبدونه يبقى الملف الحالي على الشاشة. مُفعّل افتراضيًا.",
            "चुनने पर कॉपी के तुरंत बाद प्रोग्राम अगली फ़ाइल दिखाता है। चुनाव हटाने पर मौजूदा फ़ाइल बनी रहती है। डिफ़ॉल्ट रूप से चालू।",
            "নির্বাচিত হলে কপির পরপরই প্রোগ্রাম পরের ফাইল দেখায়। টিক না থাকলে বর্তমান ফাইলই থাকে। ডিফল্টে চালু।",
            "منتخب ہونے پر پروگرام نقل کے فوراً بعد اگلی فائل دکھاتا ہے۔ نشان ہٹانے پر موجودہ فائل برقرار رہتی ہے۔ ڈیفالٹ میں فعال۔",
            "勾选后，复制完成即显示下一个文件；取消勾选则停留在当前文件。默认开启。")
        Add("Если отмечено, файловые операции уходят в фоновый поток, чтобы не заставлять вас смотреть на них.",
            "If checked, file operations run in the background, so you don't have to watch them happen.",
            "Якщо позначено, файлові операції виконуються у фоні, щоб не змушувати вас на них дивитися.",
            "Wenn aktiviert, laufen Dateivorgänge im Hintergrund, damit Sie ihnen nicht zusehen müssen.",
            "Se selezionato, le operazioni sui file girano in background, così non devi guardarle.",
            "Si está marcado, las operaciones de archivo se ejecutan en segundo plano y no tiene que mirarlas.",
            "Si coché, les opérations sur les fichiers s'exécutent en arrière-plan, vous évitant le spectacle.",
            "Se marcado, as operações de arquivo rodam em segundo plano, sem você ter que assistir.",
            "عند التحديد، تعمل عمليات الملفات في الخلفية فلا تضطر لمشاهدتها.",
            "चुनने पर फ़ाइल कार्य पृष्ठभूमि में चलते हैं, आपको देखना नहीं पड़ता।",
            "নির্বাচিত হলে ফাইল অপারেশন পটভূমিতে চলে, আপনাকে তাকিয়ে থাকতে হয় না।",
            "منتخب ہونے پر فائل کے عمل پس منظر میں چلتے ہیں، آپ کو دیکھنا نہیں پڑتا۔",
            "勾选后文件操作在后台运行，你不必盯着看。")
        Add("Выберите цветовую схему фона для просмотра изображений.",
            "Select the background color scheme for the image viewer.",
            "Виберіть колірну схему фону для перегляду зображень.",
            "Wählen Sie das Hintergrundfarbschema für die Bildanzeige.",
            "Scegli lo schema di colori dello sfondo per la visualizzazione delle immagini.",
            "Seleccione el esquema de color del fondo para el visor de imágenes.",
            "Choisissez le jeu de couleurs de fond pour la visionneuse d'images.",
            "Selecione o esquema de cores do fundo para o visualizador de imagens.",
            "اختر نظام ألوان الخلفية لعارض الصور.", "छवि दर्शक के लिए पृष्ठभूमि रंग योजना चुनें।",
            "ছবি দর্শকের জন্য পটভূমির রঙের স্কিম নির্বাচন করুন।",
            "تصویر ویور کے لیے پس منظر کا رنگ منتخب کریں۔", "选择图片查看器的背景配色方案。")
        Add("Включить перспективный фон: чёрные поля по краям превращаются в продолжение картинки. Чисто для красоты.",
            "Enable the perspective background: the black bars become a continuation of the image. Purely for the vibes.",
            "Увімкнути перспективний фон: чорні поля стають продовженням зображення. Суто для краси.",
            "Perspektivischen Hintergrund aktivieren: die schwarzen Balken werden zur Fortsetzung des Bildes. Rein der Optik wegen.",
            "Attiva lo sfondo prospettico: le bande nere diventano la continuazione dell'immagine. Puramente estetico.",
            "Activar el fondo en perspectiva: las bandas negras se convierten en continuación de la imagen. Solo por estética.",
            "Activer le fond en perspective : les bandes noires deviennent le prolongement de l'image. Purement esthétique.",
            "Ativar o fundo em perspectiva: as barras pretas viram continuação da imagem. Puramente estético.",
            "تفعيل الخلفية المنظورية: تتحول الأشرطة السوداء إلى امتداد للصورة. لأجل الجمال فقط.",
            "परिप्रेक्ष्य पृष्ठभूमि चालू करें: काली पट्टियाँ छवि का विस्तार बन जाती हैं। बस सुंदरता के लिए।",
            "পরিপ্রেক্ষিত পটভূমি চালু করুন: কালো বার ছবির ধারাবাহিকতা হয়ে যায়। শুধুই সৌন্দর্যের জন্য।",
            "تناظری پس منظر آن کریں: سیاہ پٹیاں تصویر کا تسلسل بن جاتی ہیں۔ صرف خوبصورتی کے لیے۔",
            "启用透视背景：黑边会变成画面的延续。纯粹为了好看。")
        Add("Полосы гаснут к цвету фона по мере удаления от фото - получается ореол, а не сплошная полоса. Применяется со следующего фото.",
            "The bars fade into the background colour the further they get from the photo - a halo rather than a solid bar. Applies from the next photo on.",
            "Смуги згасають до кольору фону в міру віддалення від фото - виходить ореол, а не суцільна смуга. Застосовується з наступного фото.",
            "Die Balken verblassen mit zunehmendem Abstand zum Foto in die Hintergrundfarbe - ein Halo statt eines massiven Balkens. Gilt ab dem nächsten Foto.",
            "Le bande sfumano verso il colore di sfondo allontanandosi dalla foto: un alone anziché una banda piena. Vale dalla foto successiva.",
            "Las bandas se difuminan hacia el color de fondo al alejarse de la foto: un halo en vez de una banda sólida. Se aplica desde la siguiente foto.",
            "Les bandes s'estompent vers la couleur de fond en s'éloignant de la photo - un halo plutôt qu'une bande pleine. S'applique dès la photo suivante.",
            "As barras se dissolvem na cor de fundo conforme se afastam da foto - um halo em vez de uma barra sólida. Vale a partir da próxima foto.",
            "تتلاشى الأشرطة نحو لون الخلفية كلما ابتعدت عن الصورة - هالة بدل شريط صلب. يسري من الصورة التالية.",
            "पट्टियाँ फ़ोटो से दूर जाते हुए पृष्ठभूमि रंग में मिल जाती हैं - ठोस पट्टी के बजाय आभा। अगली फ़ोटो से लागू।",
            "বারগুলো ছবি থেকে দূরে গিয়ে পটভূমির রঙে মিশে যায় - কঠিন বার নয়, আভা। পরবর্তী ছবি থেকে কার্যকর।",
            "پٹیاں تصویر سے دور ہوتے ہوئے پس منظر کے رنگ میں گھل جاتی ہیں - ٹھوس پٹی کے بجائے ہالہ۔ اگلی تصویر سے لاگو۔",
            "色带随着远离照片渐隐为背景色 - 是光晕而非实心色块。从下一张照片起生效。")
        Add("Ореол не появляется сразу, а вырастает от края фото к краю экрана - длительность выбирается ниже. Снимите галку, и он будет просто нарисован мгновенно. В покое кадр в обоих случаях одинаковый. Растёт только на новом фото: ресайз окна и зум перерисовывают фон сразу.",
            "The halo grows from the edge of the photo out to the edge of the screen - the duration is chosen below - instead of just being there. Uncheck it and it is simply drawn at once. The resting frame is the same either way. Only a new photo grows it: resizing the window or zooming redraws the background instantly.",
            "Ореол не з'являється одразу, а виростає від краю фото до краю екрана - тривалість обирається нижче. Зніміть позначку, і він просто намалюється миттєво. У спокої кадр однаковий в обох випадках. Росте лише на новому фото: зміна розміру вікна та зум перемальовують фон одразу.",
            "Der Halo wächst vom Rand des Fotos zum Bildschirmrand - die Dauer wird unten gewählt - statt einfach da zu sein. Ohne Haken wird er sofort gezeichnet. Das ruhende Bild ist so oder so identisch. Nur ein neues Foto lässt ihn wachsen: Fenstergröße und Zoom zeichnen den Hintergrund sofort neu.",
            "L'alone cresce dal bordo della foto fino al bordo dello schermo - la durata si sceglie qui sotto - invece di essere già lì. Togli la spunta e viene disegnato subito. Il fotogramma a riposo è identico in entrambi i casi. Cresce solo su una foto nuova: ridimensionare la finestra o lo zoom ridisegnano lo sfondo all'istante.",
            "El halo crece desde el borde de la foto hasta el borde de la pantalla - la duración se elige más abajo - en lugar de aparecer ya hecho. Desmárquelo y se dibujará al instante. El fotograma en reposo es idéntico en ambos casos. Solo crece con una foto nueva: redimensionar la ventana o el zoom redibujan el fondo de inmediato.",
            "Le halo croît du bord de la photo vers le bord de l'écran - la durée se choisit ci-dessous - au lieu d'être simplement là. Décochez et il est dessiné aussitôt. L'image au repos est identique dans les deux cas. Seule une nouvelle photo le fait croître : redimensionner la fenêtre ou zoomer redessine le fond immédiatement.",
            "O halo cresce da borda da foto até a borda da tela - a duração é escolhida abaixo - em vez de já estar lá. Desmarque e ele é desenhado de uma vez. O quadro em repouso é igual nos dois casos. Só uma foto nova o faz crescer: redimensionar a janela ou dar zoom redesenha o fundo na hora.",
            "تنمو الهالة من حافة الصورة إلى حافة الشاشة - وتُختار المدة أدناه - بدل أن تكون موجودة فورًا. أزل التحديد فتُرسم مباشرة. الإطار الساكن واحد في الحالتين. تنمو فقط مع صورة جديدة: تغيير حجم النافذة أو التكبير يعيد رسم الخلفية فورًا.",
            "आभा फ़ोटो के किनारे से स्क्रीन के किनारे तक बढ़ती है - अवधि नीचे चुनी जाती है - बजाय पहले से मौजूद होने के। निशान हटाने पर वह तुरंत खींच दी जाती है। स्थिर फ़्रेम दोनों हाल में एक जैसा है। केवल नई फ़ोटो पर बढ़ती है: विंडो का आकार बदलना या ज़ूम पृष्ठभूमि तुरंत दोबारा खींचते हैं।",
            "আভা ছবির প্রান্ত থেকে পর্দার প্রান্ত পর্যন্ত বাড়ে - সময়কাল নিচে বেছে নেওয়া হয় - আগে থেকে থাকার বদলে। টিক তুলে দিলে সঙ্গে সঙ্গে আঁকা হয়। স্থির ফ্রেম দুই ক্ষেত্রেই একই। কেবল নতুন ছবিতেই বাড়ে: উইন্ডো রিসাইজ বা জুম পটভূমি সঙ্গে সঙ্গে আঁকে।",
            "ہالہ تصویر کے کنارے سے اسکرین کے کنارے تک بڑھتا ہے - دورانیہ نیچے منتخب ہوتا ہے - پہلے سے موجود ہونے کے بجائے۔ نشان ہٹائیں تو فوراً بن جاتا ہے۔ ساکن فریم دونوں صورتوں میں یکساں ہے۔ صرف نئی تصویر پر بڑھتا ہے: ونڈو کا سائز بدلنا یا زوم پس منظر فوراً دوبارہ بناتے ہیں۔",
            "光晕从照片边缘向屏幕边缘生长 - 时长在下方选择 - 而不是一开始就在那里。取消勾选则立即绘制。静止时两者画面完全相同。只有新照片才会生长：调整窗口大小或缩放会立刻重绘背景。")
        Add("Как быстро ореол вырастает у нового фото. Средняя - вдвое быстрее прежней анимации, быстрая - вчетверо. На вид ореола в покое это не влияет.",
            "How fast the halo grows on a new photo. Medium is twice the speed of the old animation, fast is four times. The halo at rest looks the same either way.",
            "Як швидко ореол виростає на новому фото. Середня вдвічі швидша за колишню анімацію, швидка - вчетверо. На вигляд ореолу в спокої це не впливає.",
            "Wie schnell der Halo bei einem neuen Foto wächst. Mittel ist doppelt so schnell wie die bisherige Animation, schnell viermal. Der ruhende Halo sieht in beiden Fällen gleich aus.",
            "Quanto velocemente l'alone cresce su una foto nuova. Media è il doppio della vecchia animazione, veloce il quadruplo. L'alone a riposo resta identico.",
            "Con qué rapidez crece el halo en una foto nueva. Media es el doble de rápida que la animación anterior; rápida, cuatro veces. El halo en reposo no cambia.",
            "À quelle vitesse le halo croît sur une nouvelle photo. Moyenne est deux fois plus rapide que l'ancienne animation, rapide quatre fois. Le halo au repos reste identique.",
            "Com que rapidez o halo cresce em uma foto nova. Média é o dobro da animação anterior; rápida, o quádruplo. O halo em repouso continua igual.",
            "سرعة نمو الهالة عند فتح صورة جديدة. المتوسطة ضعف سرعة الحركة السابقة، والسريعة أربعة أضعافها. لا يتغير شكل الهالة الساكنة.",
            "नई फ़ोटो पर आभा कितनी तेज़ी से बढ़ती है। मध्यम पुरानी एनिमेशन से दोगुनी तेज़ है, तेज़ चार गुनी। स्थिर आभा दोनों हाल में एक जैसी रहती है।",
            "নতুন ছবিতে আভা কত দ্রুত বাড়ে। মাঝারি আগের অ্যানিমেশনের দ্বিগুণ দ্রুত, দ্রুত চার গুণ। স্থির আভা দুই ক্ষেত্রেই একই থাকে।",
            "نئی تصویر پر ہالہ کتنی تیزی سے بڑھتا ہے۔ درمیانی پرانی حرکت سے دوگنی تیز ہے، تیز چار گنا۔ ساکن ہالہ دونوں صورتوں میں ایک جیسا رہتا ہے۔",
            "新照片上光晕生长的快慢。中等是原动画速度的两倍，快速是四倍。静止时的光晕不受影响。")
        Add("Показывать размеры изображения (ширина x высота).",
            "Show the dimensions (width x height) of the image.",
            "Показувати розміри зображення (ширина x висота).",
            "Bildabmessungen anzeigen (Breite x Höhe).", "Mostra le dimensioni dell'immagine (larghezza x altezza).",
            "Mostrar las dimensiones de la imagen (ancho x alto).",
            "Afficher les dimensions de l'image (largeur x hauteur).",
            "Mostrar as dimensões da imagem (largura x altura).", "إظهار أبعاد الصورة (العرض × الارتفاع).",
            "छवि के आयाम दिखाएँ (चौड़ाई x ऊँचाई)।", "ছবির মাত্রা দেখান (প্রস্থ x উচ্চতা)।",
            "تصویر کے ابعاد دکھائیں (چوڑائی x اونچائی)۔", "显示图片尺寸（宽 x 高）。")
        Add("Показывать дату и время последнего изменения файла.",
            "Show the last modified date and time of the file.",
            "Показувати дату й час останньої зміни файлу.",
            "Datum und Uhrzeit der letzten Dateiänderung anzeigen.",
            "Mostra data e ora dell'ultima modifica del file.",
            "Mostrar la fecha y hora de la última modificación del archivo.",
            "Afficher la date et l'heure de dernière modification du fichier.",
            "Mostrar a data e a hora da última modificação do arquivo.",
            "إظهار تاريخ ووقت آخر تعديل للملف.", "फ़ाइल के अंतिम संशोधन की तिथि और समय दिखाएँ।",
            "ফাইলের শেষ পরিবর্তনের তারিখ ও সময় দেখান।",
            "فائل کی آخری تبدیلی کی تاریخ اور وقت دکھائیں۔", "显示文件的最后修改日期和时间。")
        Add("Показывать размер файла.", "Show the size of the file.", "Показувати розмір файлу.",
            "Dateigröße anzeigen.", "Mostra la dimensione del file.", "Mostrar el tamaño del archivo.",
            "Afficher la taille du fichier.", "Mostrar o tamanho do arquivo.", "إظهار حجم الملف.",
            "फ़ाइल का आकार दिखाएँ।", "ফাইলের আকার দেখান।", "فائل کا سائز دکھائیں۔", "显示文件大小。")
        Add("Крутить видео по кругу - пока вам не надоест или не кончится терпение.",
            "Loop the video - until you get bored or your patience runs out.",
            "Крутити відео по колу - доки вам не набридне або не скінчиться терпіння.",
            "Video in Schleife - bis Ihnen langweilig wird oder die Geduld ausgeht.",
            "Ripeti il video in loop - finché non ti annoi o finisce la pazienza.",
            "Reproducir el vídeo en bucle: hasta que se aburra o se le acabe la paciencia.",
            "Lire la vidéo en boucle - jusqu'à l'ennui ou la fin de votre patience.",
            "Repetir o vídeo em loop - até você enjoar ou acabar a paciência.",
            "تكرار الفيديو - حتى تملّ أو ينفد صبرك.",
            "वीडियो को दोहराते रहें - जब तक आप ऊब न जाएँ या धैर्य न टूटे।",
            "ভিডিও লুপে চালান - যতক্ষণ না আপনি ক্লান্ত হন বা ধৈর্য ফুরায়।",
            "ویڈیو کو دہراتے رہیں - جب تک آپ اکتا نہ جائیں یا صبر ختم نہ ہو۔",
            "循环播放视频 - 直到你腻了或耐心耗尽。")
        Add("Отключить подтверждения перед файловыми операциями. Программа поверит, что вы знаете, что делаете - смелое допущение.",
            "Skip confirmations before file operations. The app will trust that you know what you're doing - a bold assumption.",
            "Вимкнути підтвердження перед файловими операціями. Програма повірить, що ви знаєте, що робите - сміливе припущення.",
            "Bestätigungen vor Dateivorgängen überspringen. Die App vertraut darauf, dass Sie wissen, was Sie tun - eine kühne Annahme.",
            "Salta le conferme prima delle operazioni sui file. L'app darà per scontato che tu sappia cosa fai - ipotesi audace.",
            "Omitir las confirmaciones antes de las operaciones de archivo. La aplicación confiará en que usted sabe lo que hace: una suposición audaz.",
            "Ignorer les confirmations avant les opérations sur les fichiers. L'application supposera que vous savez ce que vous faites - hypothèse audacieuse.",
            "Pular as confirmações antes das operações de arquivo. O app vai confiar que você sabe o que faz - suposição ousada.",
            "تخطّي التأكيدات قبل عمليات الملفات. سيثق التطبيق بأنك تعرف ما تفعل - افتراض جريء.",
            "फ़ाइल कार्यों से पहले पुष्टि छोड़ें। ऐप मान लेगा कि आप जानते हैं कि क्या कर रहे हैं - बड़ा भरोसा।",
            "ফাইল অপারেশনের আগে নিশ্চিতকরণ বাদ দিন। অ্যাপ ধরে নেবে আপনি জানেন কী করছেন - সাহসী অনুমান।",
            "فائل کے عمل سے پہلے تصدیق چھوڑیں۔ ایپ مان لے گی کہ آپ جانتے ہیں کیا کر رہے ہیں - بڑا اعتماد۔",
            "跳过文件操作前的确认。程序会相信你知道自己在做什么 - 一个大胆的假设。")
        Add("Выберите размер карточки для формы панели изображений",
            "Choose the size of the card for the image panel", "Виберіть розмір картки для панелі зображень",
            "Größe der Karte für die Bildleiste wählen", "Scegli la dimensione della scheda del pannello immagini",
            "Elija el tamaño de la tarjeta del panel de imágenes",
            "Choisissez la taille de la vignette du panneau d'images",
            "Escolha o tamanho do cartão do painel de imagens", "اختر حجم البطاقة في لوحة الصور",
            "छवि पैनल के कार्ड का आकार चुनें", "ছবির প্যানেলের কার্ডের আকার নির্বাচন করুন",
            "تصویری پینل کے کارڈ کا سائز منتخب کریں", "选择图片面板卡片的大小")
        Add("Автоматически поворачивать фото по тегу EXIF Orientation (снимки с телефонов/камер).",
            "Auto-rotate photos by their EXIF Orientation tag (photos from phones/cameras).",
            "Автоматично повертати фото за тегом EXIF Orientation (знімки з телефонів/камер).",
            "Fotos automatisch nach dem EXIF-Orientation-Tag drehen (Aufnahmen von Handys/Kameras).",
            "Ruota automaticamente le foto secondo il tag EXIF Orientation (scatti da telefoni/fotocamere).",
            "Girar automáticamente las fotos según la etiqueta EXIF Orientation (fotos de móviles o cámaras).",
            "Faire pivoter automatiquement les photos selon la balise EXIF Orientation (photos de téléphones/appareils).",
            "Girar fotos automaticamente pela tag EXIF Orientation (fotos de celulares/câmeras).",
            "تدوير الصور تلقائيًا حسب وسم EXIF Orientation (صور الهواتف/الكاميرات).",
            "EXIF Orientation टैग के अनुसार फ़ोटो अपने-आप घुमाएँ (फ़ोन/कैमरे की तस्वीरें)।",
            "EXIF Orientation ট্যাগ অনুযায়ী ছবি স্বয়ংক্রিয়ভাবে ঘোরান (ফোন/ক্যামেরার ছবি)।",
            "EXIF Orientation ٹیگ کے مطابق تصاویر خودکار گھمائیں (فون/کیمرے کی تصاویر)۔",
            "根据 EXIF Orientation 标签自动旋转照片（手机/相机拍摄）。")
        Add("Качественное (бикубическое) масштабирование - резче при уменьшении крупных изображений.",
            "High-quality (bicubic) scaling - sharper when downscaling large images.",
            "Якісне (бікубічне) масштабування - різкіше при зменшенні великих зображень.",
            "Hochwertige (bikubische) Skalierung - schärfer beim Verkleinern großer Bilder.",
            "Ridimensionamento di qualità (bicubico) - più nitido riducendo immagini grandi.",
            "Escalado de alta calidad (bicúbico): más nítido al reducir imágenes grandes.",
            "Mise à l'échelle de qualité (bicubique) - plus net lors de la réduction de grandes images.",
            "Redimensionamento de alta qualidade (bicúbico) - mais nítido ao reduzir imagens grandes.",
            "تحجيم عالي الجودة (ثنائي التكعيب) - أوضح عند تصغير الصور الكبيرة.",
            "उच्च-गुणवत्ता (बाइक्यूबिक) स्केलिंग - बड़ी छवियाँ छोटी करने पर अधिक स्पष्ट।",
            "উচ্চ-মানের (বাইকিউবিক) স্কেলিং - বড় ছবি ছোট করলে বেশি স্পষ্ট।",
            "اعلیٰ معیار کی (بائی کیوبک) اسکیلنگ - بڑی تصاویر چھوٹی کرنے پر زیادہ واضح۔",
            "高质量（双三次）缩放 - 缩小大图时更锐利。")
        Add("Показывать имя файла и позицию (N/всего) поверх изображения. Удобно в полноэкранном режиме, где статусбар стыдливо прячется.",
            "Show the file name and position (N/total) over the image. Handy in full-screen, where the status bar shyly hides.",
            "Показувати ім'я файлу та позицію (N/усього) поверх зображення. Зручно в повноекранному режимі, де рядок стану сором'язливо ховається.",
            "Dateiname und Position (N/gesamt) über dem Bild anzeigen. Praktisch im Vollbild, wo sich die Statusleiste schüchtern versteckt.",
            "Mostra il nome del file e la posizione (N/totale) sopra l'immagine. Comodo a schermo intero, dove la barra di stato si nasconde timidamente.",
            "Mostrar el nombre del archivo y la posición (N/total) sobre la imagen. Útil a pantalla completa, donde la barra de estado se esconde tímidamente.",
            "Afficher le nom du fichier et la position (N/total) sur l'image. Pratique en plein écran, où la barre d'état se cache timidement.",
            "Mostrar o nome do arquivo e a posição (N/total) sobre a imagem. Útil em tela cheia, onde a barra de status se esconde timidamente.",
            "إظهار اسم الملف والموضع (N/الإجمالي) فوق الصورة. مفيد في ملء الشاشة حيث يختبئ شريط الحالة بخجل.",
            "छवि पर फ़ाइल का नाम और स्थिति (N/कुल) दिखाएँ। पूर्ण-स्क्रीन में उपयोगी, जहाँ स्टेटस बार शर्माकर छिप जाता है।",
            "ছবির উপরে ফাইলের নাম ও অবস্থান (N/মোট) দেখান। পূর্ণ-স্ক্রিনে কাজে লাগে, যেখানে স্ট্যাটাস বার লজ্জা পেয়ে লুকায়।",
            "تصویر پر فائل کا نام اور مقام (N/کل) دکھائیں۔ فل اسکرین میں مفید، جہاں اسٹیٹس بار شرما کر چھپ جاتا ہے۔",
            "在图片上显示文件名和位置（N/总数）。全屏时很有用 - 那时状态栏会害羞地躲起来。")
        Add("Как в привычных просмотрщиках: колесо приближает и отдаляет под курсором. Выключено - колесо листает файлы, как было всегда. В любом случае Ctrl+колесо приближает, Shift+колесо даёт 100 %, Alt+колесо вписывает, а над видео колесо всегда листает. С клавиатуры: серые +/- приближают от курсора, / вписывает, * даёт 100 %.",
            "Like the viewers you are used to: the wheel zooms in and out under the cursor. Off - the wheel flips through files, exactly as it always has. Either way Ctrl+wheel zooms, Shift+wheel gives 100 %, Alt+wheel fits, and over video the wheel always flips. From the keyboard: NumPad +/- zoom at the cursor, / fits, * gives 100 %.",
            "Як у звичних переглядачах: колесо наближає й віддаляє під курсором. Вимкнено - колесо гортає файли, як було завжди. У будь-якому разі Ctrl+колесо наближає, Shift+колесо дає 100 %, Alt+колесо вписує, а над відео колесо завжди гортає. З клавіатури: сірі +/- наближають від курсора, / вписує, * дає 100 %.",
            "Wie in gewohnten Betrachtern: das Rad zoomt unter dem Cursor. Aus - das Rad blättert durch Dateien, wie schon immer. So oder so zoomt Strg+Rad, Umschalt+Rad gibt 100 %, Alt+Rad passt ein, und über Video blättert das Rad immer. Über Tastatur: NumPad +/- zoomen am Cursor, / passt ein, * gibt 100 %.",
            "Come nei visualizzatori a cui sei abituato: la rotella ingrandisce e riduce sotto il cursore. Disattivo - la rotella sfoglia i file, come è sempre stato. In ogni caso Ctrl+rotella ingrandisce, Maiusc+rotella dà 100 %, Alt+rotella adatta, e sul video la rotella sfoglia sempre. Da tastiera: +/- del tastierino ingrandiscono al cursore, / adatta, * dà 100 %.",
            "Como en los visores habituales: la rueda acerca y aleja bajo el cursor. Desactivado, la rueda pasa archivos, como siempre. En cualquier caso Ctrl+rueda amplía, Mayús+rueda da 100 %, Alt+rueda ajusta, y sobre el vídeo la rueda siempre pasa archivos. Desde el teclado: +/- del teclado numérico amplían en el cursor, / ajusta, * da 100 %.",
            "Comme dans les visionneuses habituelles : la molette zoome sous le curseur. Désactivé - la molette fait défiler les fichiers, comme toujours. Dans tous les cas Ctrl+molette zoome, Maj+molette donne 100 %, Alt+molette ajuste, et sur une vidéo la molette fait toujours défiler. Au clavier : +/- du pavé numérique zooment au curseur, / ajuste, * donne 100 %.",
            "Como nos visualizadores de sempre: a roda amplia e reduz sob o cursor. Desligado - a roda passa arquivos, como sempre foi. De todo modo Ctrl+roda amplia, Shift+roda dá 100 %, Alt+roda ajusta, e sobre vídeo a roda sempre passa. No teclado: +/- do numérico ampliam no cursor, / ajusta, * dá 100 %.",
            "كما في العارضات المعتادة: العجلة تكبّر وتصغّر تحت المؤشر. عند الإيقاف تتنقل العجلة بين الملفات كما كانت دائمًا. في الحالتين Ctrl+عجلة يكبّر، Shift+عجلة يعطي 100 %، Alt+عجلة يلائم، وفوق الفيديو تتنقل العجلة دائمًا. من لوحة المفاتيح: ‎+/-‎ في اللوحة الرقمية تكبّر عند المؤشر، ‎/‎ يلائم، ‎*‎ يعطي 100 %.",
            "जैसे आम व्यूअर में होता है: पहिया कर्सर के नीचे ज़ूम करता है। बंद होने पर पहिया फ़ाइलें बदलता है, हमेशा की तरह। दोनों हाल में Ctrl+पहिया ज़ूम करता है, Shift+पहिया 100 % देता है, Alt+पहिया फ़िट करता है, और वीडियो पर पहिया हमेशा फ़ाइल बदलता है। कीबोर्ड से: NumPad +/- कर्सर पर ज़ूम, / फ़िट, * 100 %।",
            "পরিচিত ভিউয়ারের মতো: চাকা কার্সরের নিচে জুম করে। বন্ধ থাকলে চাকা ফাইল পাল্টায়, যেমন সবসময় হতো। যেভাবেই হোক Ctrl+চাকা জুম করে, Shift+চাকা 100 % দেয়, Alt+চাকা ফিট করে, আর ভিডিওতে চাকা সবসময় ফাইল পাল্টায়। কীবোর্ড থেকে: NumPad +/- কার্সরে জুম, / ফিট, * 100 %।",
            "عام ویورز کی طرح: پہیہ کرسر کے نیچے زوم کرتا ہے۔ بند ہونے پر پہیہ فائلیں بدلتا ہے، جیسے ہمیشہ ہوتا تھا۔ بہرحال Ctrl+پہیہ زوم کرتا ہے، Shift+پہیہ 100 % دیتا ہے، Alt+پہیہ فٹ کرتا ہے، اور ویڈیو پر پہیہ ہمیشہ فائل بدلتا ہے۔ کی بورڈ سے: NumPad ‎+/-‎ کرسر پر زوم، ‎/‎ فٹ، ‎*‎ 100 %۔",
            "和你熟悉的看图软件一样：滚轮在光标处缩放。关闭时滚轮翻页浏览文件，一如既往。无论哪种，Ctrl+滚轮缩放，Shift+滚轮为 100 %，Alt+滚轮适应窗口，而在视频上滚轮始终翻页。键盘操作：小键盘 +/- 在光标处缩放，/ 适应窗口，* 为 100 %。")
        Add("Базовый интервал слайдшоу в секундах. Запустите слайдшоу ещё раз - и оно ускорится вдвое, будто куда-то опаздывает.",
            "Base slideshow interval in seconds. Start the slideshow again and it halves the delay, as if it's late for something.",
            "Базовий інтервал слайд-шоу в секундах. Запустіть слайд-шоу ще раз - і воно прискориться вдвічі, наче кудись запізнюється.",
            "Basisintervall der Diashow in Sekunden. Starten Sie die Diashow erneut, halbiert sich die Verzögerung, als käme sie zu spät.",
            "Intervallo base della presentazione in secondi. Riavvia la presentazione e il ritardo si dimezza, come se fosse in ritardo per qualcosa.",
            "Intervalo base del pase de diapositivas en segundos. Vuelva a iniciarlo y el retardo se reduce a la mitad, como si llegara tarde a algo.",
            "Intervalle de base du diaporama en secondes. Relancez le diaporama et le délai est divisé par deux, comme s'il était en retard.",
            "Intervalo base da apresentação em segundos. Inicie de novo e o atraso cai pela metade, como se estivesse atrasado para algo.",
            "الفاصل الأساسي لعرض الشرائح بالثواني. ابدأ العرض مرة أخرى فينخفض التأخير إلى النصف، وكأنه متأخر عن موعد.",
            "स्लाइडशो का आधार अंतराल सेकंड में। स्लाइडशो फिर शुरू करें और देरी आधी हो जाती है, मानो कहीं देर हो रही हो।",
            "স্লাইডশোর মূল বিরতি সেকেন্ডে। স্লাইডশো আবার চালু করলে বিলম্ব অর্ধেক হয়, যেন কোথাও দেরি হয়ে যাচ্ছে।",
            "سلائیڈ شو کا بنیادی وقفہ سیکنڈوں میں۔ سلائیڈ شو دوبارہ شروع کریں تو تاخیر آدھی ہو جاتی ہے، جیسے کہیں دیر ہو رہی ہو۔",
            "幻灯片的基础间隔（秒）。再启动一次幻灯片，间隔就减半 - 像是赶时间似的。")
        Add("Запускать видео без звука - для просмотра в приличном обществе.",
            "Start videos muted - for viewing in polite company.",
            "Запускати відео без звуку - для перегляду в пристойному товаристві.",
            "Videos stumm starten - für das Ansehen in höflicher Gesellschaft.",
            "Avvia i video senza audio - per guardarli in buona compagnia.",
            "Iniciar los vídeos silenciados: para verlos en buena compañía.",
            "Démarrer les vidéos en sourdine - pour un visionnage en bonne compagnie.",
            "Iniciar os vídeos sem som - para assistir em boa companhia.",
            "تشغيل الفيديو صامتًا - للمشاهدة في صحبة مهذبة.",
            "वीडियो बिना आवाज़ शुरू करें - शिष्ट संगत में देखने के लिए।",
            "ভিডিও শব্দ ছাড়া চালু করুন - ভদ্র সঙ্গে দেখার জন্য।",
            "ویڈیو بغیر آواز شروع کریں - مہذب محفل میں دیکھنے کے لیے۔",
            "视频静音开始播放 - 方便在体面场合观看。")
        Add("Громкость видео по умолчанию (0-100%).", "Default video volume (0-100%).",
            "Гучність відео за замовчуванням (0-100%).", "Standardlautstärke für Video (0-100 %).",
            "Volume video predefinito (0-100%).", "Volumen de vídeo predeterminado (0-100 %).",
            "Volume vidéo par défaut (0-100 %).", "Volume padrão do vídeo (0-100%).",
            "مستوى صوت الفيديو الافتراضي (0-100%).", "डिफ़ॉल्ट वीडियो ध्वनि (0-100%)।",
            "ডিফল্ট ভিডিও ভলিউম (0-100%)।", "ڈیفالٹ ویڈیو آواز (0-100%)۔", "默认视频音量（0-100%）。")
        Add("Плавающий список каталогов-получателей в левом верхнем углу поверх изображения/видео. Клик по строке - перенести/скопировать текущий файл в эту папку (или удалить). По умолчанию выключено.",
            "Floating list of destination folders, top-left over the image/video. Click a row to move/copy the current file there (or delete it). Off by default.",
            "Плаваючий список тек-отримувачів у лівому верхньому куті поверх зображення/відео. Клік по рядку - перенести/скопіювати поточний файл до цієї теки (або видалити). Типово вимкнено.",
            "Schwebende Liste der Zielordner, oben links über Bild/Video. Klick auf eine Zeile verschiebt/kopiert die aktuelle Datei dorthin (oder löscht sie). Standardmäßig aus.",
            "Elenco flottante delle cartelle di destinazione, in alto a sinistra sopra immagine/video. Clic su una riga per spostare/copiare lì il file corrente (o eliminarlo). Disattivo per impostazione predefinita.",
            "Lista flotante de carpetas de destino, arriba a la izquierda sobre la imagen o el vídeo. Haga clic en una fila para mover o copiar allí el archivo actual (o eliminarlo). Desactivado de forma predeterminada.",
            "Liste flottante des dossiers de destination, en haut à gauche par-dessus l'image/la vidéo. Cliquez sur une ligne pour y déplacer/copier le fichier courant (ou le supprimer). Désactivé par défaut.",
            "Lista flutuante de pastas de destino, no canto superior esquerdo sobre a imagem/vídeo. Clique numa linha para mover/copiar o arquivo atual para lá (ou excluí-lo). Desligado por padrão.",
            "قائمة عائمة بمجلدات الوجهة أعلى اليسار فوق الصورة/الفيديو. انقر صفًا لنقل/نسخ الملف الحالي إليه (أو حذفه). معطّل افتراضيًا.",
            "गंतव्य फ़ोल्डरों की तैरती सूची, छवि/वीडियो के ऊपर बाईं ओर। किसी पंक्ति पर क्लिक कर मौजूदा फ़ाइल वहाँ ले जाएँ/कॉपी करें (या हटाएँ)। डिफ़ॉल्ट रूप से बंद।",
            "গন্তব্য ফোল্ডারের ভাসমান তালিকা, ছবি/ভিডিওর উপরে বাঁ দিকে। সারিতে ক্লিক করে বর্তমান ফাইল সেখানে সরান/কপি করুন (বা মুছুন)। ডিফল্টে বন্ধ।",
            "منزل فولڈرز کی تیرتی فہرست، تصویر/ویڈیو کے اوپر بائیں جانب۔ کسی قطار پر کلک کر کے موجودہ فائل وہاں منتقل/نقل کریں (یا حذف کریں)۔ ڈیفالٹ میں بند۔",
            "目标文件夹的浮动列表，位于图片/视频左上方。点击某行即可将当前文件移动/复制到该文件夹（或删除）。默认关闭。")
        Add("Открыть параметры Windows для назначения программы просмотра изображений по умолчанию.",
            "Open Windows settings to set the default image viewer.",
            "Відкрити параметри Windows, щоб призначити програму перегляду зображень за замовчуванням.",
            "Windows-Einstellungen öffnen, um den Standard-Bildbetrachter festzulegen.",
            "Apri le impostazioni di Windows per impostare il visualizzatore di immagini predefinito.",
            "Abrir la configuración de Windows para establecer el visor de imágenes predeterminado.",
            "Ouvrir les paramètres Windows pour définir la visionneuse d'images par défaut.",
            "Abrir as configurações do Windows para definir o visualizador de imagens padrão.",
            "افتح إعدادات Windows لتعيين عارض الصور الافتراضي.",
            "डिफ़ॉल्ट छवि दर्शक सेट करने के लिए Windows सेटिंग्स खोलें।",
            "ডিফল্ট ছবি দর্শক সেট করতে Windows সেটিংস খুলুন।",
            "ڈیفالٹ تصویر ویور مقرر کرنے کے لیے Windows ترتیبات کھولیں۔",
            "打开 Windows 设置以指定默认图片查看器。")
        Add("Сделать эту программу видеоплеером по умолчанию - для текущего пользователя, без танцев с правами администратора.",
            "Make this app the default video player - per-user, no admin-rights ritual required.",
            "Зробити цю програму відеоплеєром за замовчуванням - для поточного користувача, без танців із правами адміністратора.",
            "Diese App zum Standard-Videoplayer machen - pro Benutzer, ohne Administratorrechte-Ritual.",
            "Rendi questa app il lettore video predefinito - per utente, senza rituali di privilegi amministrativi.",
            "Hacer que esta aplicación sea el reproductor de vídeo predeterminado: por usuario, sin rituales de permisos de administrador.",
            "Faire de cette application le lecteur vidéo par défaut - par utilisateur, sans rituel de droits administrateur.",
            "Tornar este app o player de vídeo padrão - por usuário, sem ritual de direitos de administrador.",
            "اجعل هذا التطبيق مشغّل الفيديو الافتراضي - لكل مستخدم، دون طقوس صلاحيات المسؤول.",
            "इस ऐप को डिफ़ॉल्ट वीडियो प्लेयर बनाएँ - प्रति उपयोगकर्ता, बिना व्यवस्थापक अधिकारों के झंझट।",
            "এই অ্যাপকে ডিফল্ট ভিডিও প্লেয়ার করুন - প্রতি ব্যবহারকারীর জন্য, প্রশাসক অধিকারের ঝামেলা ছাড়াই।",
            "اس ایپ کو ڈیفالٹ ویڈیو پلیئر بنائیں - فی صارف، ایڈمن حقوق کے جھنجھٹ کے بغیر۔",
            "把本程序设为默认视频播放器 - 按用户设置，不用折腾管理员权限。")
        Add("Открыть отдельное приложение управления SFTP-сервером и опубликованными папками.",
            "Open the separate app for managing the SFTP server and published folders.",
            "Відкрити окремий застосунок керування SFTP-сервером і опублікованими теками.",
            "Die separate App zur Verwaltung des SFTP-Servers und der freigegebenen Ordner öffnen.",
            "Apri l'app separata per gestire il server SFTP e le cartelle pubblicate.",
            "Abrir la aplicación independiente para gestionar el servidor SFTP y las carpetas publicadas.",
            "Ouvrir l'application distincte de gestion du serveur SFTP et des dossiers publiés.",
            "Abrir o aplicativo separado para gerenciar o servidor SFTP e as pastas publicadas.",
            "افتح التطبيق المنفصل لإدارة خادم SFTP والمجلدات المنشورة.",
            "SFTP सर्वर और प्रकाशित फ़ोल्डर प्रबंधित करने के लिए अलग ऐप खोलें।",
            "SFTP সার্ভার ও প্রকাশিত ফোল্ডার পরিচালনার আলাদা অ্যাপ খুলুন।",
            "SFTP سرور اور شائع شدہ فولڈرز کے انتظام کے لیے الگ ایپ کھولیں۔",
            "打开用于管理 SFTP 服务器和已发布文件夹的独立程序。")
        Add("Версия программы и адрес автора.", "Application version and the author's email address.",
            "Версія програми та адреса автора.", "Programmversion und E-Mail-Adresse des Autors.",
            "Versione dell'applicazione e indirizzo e-mail dell'autore.",
            "Versión de la aplicación y correo del autor.",
            "Version de l'application et adresse e-mail de l'auteur.",
            "Versão do aplicativo e e-mail do autor.", "إصدار التطبيق وبريد المؤلف.",
            "ऐप का संस्करण और लेखक का ईमेल पता।", "অ্যাপের সংস্করণ ও লেখকের ইমেইল।",
            "ایپ کا ورژن اور مصنف کا ای میل۔", "程序版本与作者邮箱。")
        Add("Двойной клик по номеру клавиши - выполнить действие. Двойной клик по пути - выбрать папку.",
            "Double-click a key number to run the action. Double-click a path to pick a folder.",
            "Подвійний клік по номеру клавіші - виконати дію. Подвійний клік по шляху - вибрати теку.",
            "Doppelklick auf eine Tastennummer führt die Aktion aus. Doppelklick auf einen Pfad wählt einen Ordner.",
            "Doppio clic su un numero di tasto per eseguire l'azione. Doppio clic su un percorso per scegliere una cartella.",
            "Doble clic en un número de tecla para ejecutar la acción. Doble clic en una ruta para elegir carpeta.",
            "Double-cliquez sur un numéro de touche pour exécuter l'action. Double-cliquez sur un chemin pour choisir un dossier.",
            "Clique duas vezes num número de tecla para executar a ação. Clique duas vezes num caminho para escolher a pasta.",
            "انقر نقرًا مزدوجًا على رقم المفتاح لتنفيذ الإجراء. وعلى المسار لاختيار مجلد.",
            "क्रिया चलाने के लिए कुंजी संख्या पर डबल-क्लिक करें। फ़ोल्डर चुनने के लिए पथ पर डबल-क्लिक करें।",
            "কাজ চালাতে কী নম্বরে ডাবল-ক্লিক করুন। ফোল্ডার বাছতে পাথে ডাবল-ক্লিক করুন।",
            "عمل چلانے کے لیے کلید نمبر پر ڈبل کلک کریں۔ فولڈر منتخب کرنے کے لیے راستے پر ڈبل کلک کریں۔",
            "双击键号执行操作。双击路径选择文件夹。")
        ' Mainline: the same hint, saying which button does which action - the global copy
        ' mode is gone, so the modifier has to be spelled out.
        Add("Двойной клик по номеру клавиши - перенести файл, Shift + двойной клик - скопировать. Двойной клик по пути - выбрать папку.",
            "Double-click a key number to move the file, Shift + double-click to copy it. Double-click a path to pick a folder.",
            "Подвійний клік по номеру клавіші - перенести файл, Shift + подвійний клік - скопіювати. Подвійний клік по шляху - вибрати теку.",
            "Doppelklick auf eine Tastennummer verschiebt die Datei, Shift + Doppelklick kopiert sie. Doppelklick auf einen Pfad wählt einen Ordner.",
            "Doppio clic su un numero di tasto per spostare il file, Shift + doppio clic per copiarlo. Doppio clic su un percorso per scegliere una cartella.",
            "Doble clic en un número de tecla para mover el archivo, Shift + doble clic para copiarlo. Doble clic en una ruta para elegir carpeta.",
            "Double-cliquez sur un numéro de touche pour déplacer le fichier, Shift + double clic pour le copier. Double-cliquez sur un chemin pour choisir un dossier.",
            "Clique duas vezes num número de tecla para mover o arquivo, Shift + clique duplo para copiá-lo. Clique duas vezes num caminho para escolher a pasta.",
            "انقر نقرًا مزدوجًا على رقم المفتاح لنقل الملف، وShift + نقر مزدوج لنسخه. وانقر نقرًا مزدوجًا على المسار لاختيار مجلد.",
            "फ़ाइल ले जाने के लिए कुंजी संख्या पर डबल-क्लिक करें, कॉपी के लिए Shift + डबल-क्लिक। फ़ोल्डर चुनने के लिए पथ पर डबल-क्लिक करें।",
            "ফাইল সরাতে কী নম্বরে ডাবল-ক্লিক করুন, কপি করতে Shift + ডাবল-ক্লিক। ফোল্ডার বাছতে পাথে ডাবল-ক্লিক করুন।",
            "فائل منتقل کرنے کے لیے کلید نمبر پر ڈبل کلک کریں، نقل کے لیے Shift + ڈبل کلک۔ فولڈر منتخب کرنے کے لیے راستے پر ڈبل کلک کریں۔",
            "双击键号移动文件，Shift + 双击复制。双击路径可选择文件夹。")

        ' --- shared short captions -----------------------------------------------
        Add("По углу", "By corner", "За кутом", "Nach Ecke", "Per angolo", "Por esquina",
            "Par coin", "Por canto", "حسب الزاوية", "कोने से", "কোণ অনুযায়ী", "کونے کے حساب سے", "按角落")
        Add("Чёрный", "Black", "Чорний", "Schwarz", "Nero", "Negro", "Noir", "Preto",
            "أسود", "काला", "কালো", "سیاہ", "黑色")
        Add("Белый", "White", "Білий", "Weiß", "Bianco", "Blanco", "Blanc", "Branco",
            "أبيض", "सफ़ेद", "সাদা", "سفید", "白色")
        Add("По краю", "By side", "За краєм", "Nach Rand", "Per lato", "Por borde", "Par bord",
            "Por borda", "حسب الحافة", "किनारे से", "প্রান্ত অনুযায়ী", "کنارے کے حساب سے", "按边缘")
        Add("По верху", "By top", "За верхом", "Nach oben", "Dall'alto", "Por arriba", "Par le haut",
            "Pelo topo", "من الأعلى", "ऊपर से", "উপর থেকে", "اوپر سے", "按顶部")
        Add("По низу", "By buttom", "За низом", "Nach unten", "Dal basso", "Por abajo", "Par le bas",
            "Pela base", "من الأسفل", "नीचे से", "নিচ থেকে", "نیچے سے", "按底部")
        Add("Перспектива", "Perspective", "Перспектива", "Perspektive", "Prospettiva", "Perspectiva",
            "Perspective", "Perspectiva", "منظور", "परिप्रेक्ष्य", "পরিপ্রেক্ষিত", "تناظر", "透视")
        Add("Динамическая перспектива", "Dynamic perspective", "Динамічна перспектива",
            "Dynamische Perspektive", "Prospettiva dinamica", "Perspectiva dinámica",
            "Perspective dynamique", "Perspectiva dinâmica", "منظور ديناميكي",
            "गतिशील परिप्रेक्ष्य", "গতিশীল পরিপ্রেক্ষিত", "متحرک تناظر", "动态透视")
        Add("Анимированная", "Animated", "Анімована", "Animiert", "Animata", "Animada",
            "Animée", "Animada", "متحركة", "एनिमेटेड", "অ্যানিমেটেড", "متحرک", "动画")
        ' The three halo growth speeds, slowest first (Table_Form.vb builds the drop-down).
        Add("Медленная", "Slow", "Повільна", "Langsam", "Lenta", "Lenta",
            "Lente", "Lenta", "بطيئة", "धीमी", "ধীর", "سست", "慢速")
        Add("Средняя", "Medium", "Середня", "Mittel", "Media", "Media",
            "Moyenne", "Média", "متوسطة", "मध्यम", "মাঝারি", "درمیانی", "中等")
        Add("Быстрая", "Fast", "Швидка", "Schnell", "Veloce", "Rápida",
            "Rapide", "Rápida", "سريعة", "तेज़", "দ্রুত", "تیز", "快速")
        Add("Удаление файла", "Delete file", "Видалення файлу", "Datei löschen", "Elimina file",
            "Eliminar archivo", "Supprimer le fichier", "Excluir arquivo", "حذف الملف",
            "फ़ाइल हटाएँ", "ফাইল মুছুন", "فائل حذف کریں", "删除文件")

        Add("Разрешать запуск в новых окнах",
            "Allow launching in new windows", "Дозволяти запуск у нових вікнах", "Start in neuen Fenstern erlauben", "Consentire l'avvio in nuove finestre", "Permitir iniciar en ventanas nuevas", "Autoriser le lancement dans de nouvelles fenêtres", "Permitir iniciar em novas janelas", "السماح بالتشغيل في نوافذ جديدة", "नई विंडो में शुरू करने की अनुमति दें", "নতুন উইন্ডোতে চালুর অনুমতি দিন", "نئی ونڈوز میں چلانے کی اجازت دیں", "允许在新窗口中启动")

        AddSettingsHintStrings()
        AddOcrStrings()
    End Sub

End Class
