Option Strict On

' <summary>
' The captions of the main window itself - the toolbar buttons and the first-run
' help, which is registered one line at a time (see Main_Form.Localization.vb).
' </summary>
Partial Public NotInheritable Class Localization

    Private Shared Sub AddChromeStrings()

        ' --- toolbar --------------------------------------------------------------
        Add("Каталог:", "Folder:", "Тека:", "Ordner:", "Cartella:", "Carpeta:", "Dossier :", "Pasta:", "المجلد:", "फ़ोल्डर:", "ফোল্ডার:", "فولڈر:", "文件夹：")
        Add("<< пред(PgUp)", "<< (P)rev", "<< попер(PgUp)", "<< Zurück(Bild↑)", "<< Prec(PgSu)", "<< Ant(RePág)", "<< Préc(PgPr)", "<< Ant(PgUp)", "<< السابق(PgUp)", "<< पिछला(PgUp)", "<< আগের(PgUp)", "<< پچھلا(PgUp)", "<< 上一个(PgUp)")
        Add("след(PgDn) >>", "(N)ext >>", "наст(PgDn) >>", "Weiter(Bild↓) >>", "Succ(PgGiù) >>", "Sig(AvPág) >>", "Suiv(PgSu) >>", "Próx(PgDn) >>", "التالي(PgDn) >>", "अगला(PgDn) >>", "পরের(PgDn) >>", "اگلا(PgDn) >>", "下一个(PgDn) >>")
        Add("удалить (del)", "(D)elete", "видалити (del)", "Löschen (Entf)", "elimina (Canc)", "eliminar (Supr)", "supprimer (Suppr)", "excluir (Del)", "حذف (Del)", "हटाएँ (Del)", "মুছুন (Del)", "حذف (Del)", "删除 (Del)")

        ' --- first-run help, before the zoom block --------------------------------
        Add(" Программа для быстрого переноса/копирования изображений по папкам. Да, та самая, которой вам не хватало.",
            " Program for fast image sorting. Yes, the one you've been missing.",
            " Програма для швидкого перенесення/копіювання зображень по теках. Так, та сама, якої вам бракувало.",
            " Programm zum schnellen Verschieben/Kopieren von Bildern in Ordner. Ja, genau das, was Ihnen gefehlt hat.",
            " Programma per spostare/copiare rapidamente immagini tra cartelle. Sì, proprio quello che ti mancava.",
            " Programa para mover o copiar imágenes entre carpetas rápidamente. Sí, ese que le faltaba.",
            " Programme pour déplacer/copier rapidement des images entre dossiers. Oui, celui qui vous manquait.",
            " Programa para mover/copiar imagens entre pastas rapidamente. Sim, aquele que faltava.",
            " برنامج لنقل/نسخ الصور بين المجلدات بسرعة. نعم، ذاك الذي كان ينقصك.",
            " फ़ोल्डरों के बीच छवियाँ तेज़ी से ले जाने/कॉपी करने का प्रोग्राम। हाँ, वही जिसकी आपको कमी थी।",
            " ফোল্ডারের মাঝে দ্রুত ছবি সরানো/কপি করার প্রোগ্রাম। হ্যাঁ, সেটাই যেটার অভাব ছিল।",
            " فولڈرز کے درمیان تیزی سے تصاویر منتقل/نقل کرنے کا پروگرام۔ جی ہاں، وہی جس کی کمی تھی۔",
            " 在文件夹之间快速移动/复制图片的程序。没错，就是你一直想要的那个。")
        ' (the blank separator line needs no entry - T("") returns "" without a lookup)
        Add("Сначала заполните таблицу каталогов-получателей по клавишам 1,2,3.. - 0. ",
            "First fill the destination-folders table for keys: 1,2.. - 0. ",
            "Спочатку заповніть таблицю тек-отримувачів за клавішами 1,2,3.. - 0. ",
            "Füllen Sie zuerst die Zielordner-Tabelle für die Tasten 1,2,3.. - 0. ",
            "Prima compila la tabella delle cartelle di destinazione per i tasti 1,2,3.. - 0. ",
            "Primero rellene la tabla de carpetas de destino para las teclas 1,2,3.. - 0. ",
            "Remplissez d'abord la table des dossiers de destination pour les touches 1,2,3.. - 0. ",
            "Primeiro preencha a tabela de pastas de destino para as teclas 1,2,3.. - 0. ",
            "املأ أولاً جدول مجلدات الوجهة للمفاتيح 1,2,3.. - 0. ",
            "पहले कुंजियों 1,2,3.. - 0 के लिए गंतव्य-फ़ोल्डर तालिका भरें। ",
            "প্রথমে 1,2,3.. - 0 কী-এর জন্য গন্তব্য-ফোল্ডার টেবিল পূরণ করুন। ",
            "پہلے کلیدوں 1,2,3.. - 0 کے لیے منزل فولڈر ٹیبل بھریں۔ ",
            "先为按键 1,2,3.. - 0 填好目标文件夹表格。 ")
        Add("Затем укажите каталог-источник для сортировки (тот самый, где творится беспорядок). ",
            "Then point it at the folder with your unsorted files (you know the one). ",
            "Потім укажіть теку-джерело для сортування (ту саму, де панує безлад). ",
            "Zeigen Sie dann auf den Ordner mit den unsortierten Dateien (Sie wissen schon, welchen). ",
            "Poi indica la cartella con i file da ordinare (quella che sai tu). ",
            "Después indique la carpeta con los archivos sin ordenar (ya sabe cuál). ",
            "Indiquez ensuite le dossier contenant vos fichiers en vrac (vous savez lequel). ",
            "Depois aponte para a pasta com os arquivos bagunçados (você sabe qual). ",
            "ثم حدّد المجلد الذي فيه الملفات غير المرتبة (تعرفه جيدًا). ",
            "फिर बिना छँटे फ़ाइलों वाला फ़ोल्डर बताएँ (आप जानते ही हैं कौन सा)। ",
            "তারপর অগোছালো ফাইলের ফোল্ডারটি দেখান (আপনি জানেন কোনটা)। ",
            "پھر بغیر ترتیب فائلوں والا فولڈر بتائیں (آپ جانتے ہی ہیں کون سا)۔ ",
            "然后指向那个乱糟糟的待整理文件夹（你知道是哪个）。 ")
        Add("Продвигайтесь по файлам с помощью стрелок, P/N (PgDn/PgUp) или кликов/скролла мыши. ",
            "Move through files with P/N (PgDn/PgUp) keys or mouse clicks/scroll. ",
            "Просувайтеся по файлах за допомогою стрілок, P/N (PgDn/PgUp) або кліків/прокрутки миші. ",
            "Bewegen Sie sich mit den Pfeiltasten, P/N (Bild↓/Bild↑) oder Mausklick/Rad durch die Dateien. ",
            "Spostati tra i file con le frecce, P/N (PgGiù/PgSu) o clic/rotella del mouse. ",
            "Recorra los archivos con las flechas, P/N (AvPág/RePág) o clics y rueda del ratón. ",
            "Parcourez les fichiers avec les flèches, P/N (PgSuiv/PgPréc) ou les clics/la molette. ",
            "Percorra os arquivos com as setas, P/N (PgDn/PgUp) ou cliques/roda do mouse. ",
            "تنقّل بين الملفات بالأسهم أو P/N (PgDn/PgUp) أو بنقر/عجلة الفأرة. ",
            "तीर कुंजियों, P/N (PgDn/PgUp) या माउस क्लिक/स्क्रॉल से फ़ाइलों में चलें। ",
            "তীর কী, P/N (PgDn/PgUp) বা মাউস ক্লিক/স্ক্রলে ফাইলের মধ্যে চলুন। ",
            "تیر کی کلیدوں، P/N (PgDn/PgUp) یا ماؤس کلک/اسکرول سے فائلوں میں چلیں۔ ",
            "用方向键、P/N（PgDn/PgUp）或鼠标点击/滚轮在文件间浏览。 ")
        Add("Стрелки вверх/вниз: -10/+10 и Shift+ PgDn/PgUp: +100/-100 файлов",
            "Up/Down: -10/+10 and Shift+ PgDn/PgUp: +100/-100 files",
            "Стрілки вгору/вниз: -10/+10 і Shift+ PgDn/PgUp: +100/-100 файлів",
            "Pfeil hoch/runter: -10/+10 und Umschalt+ Bild↓/Bild↑: +100/-100 Dateien",
            "Su/Giù: -10/+10 e Maiusc+ PgGiù/PgSu: +100/-100 file",
            "Arriba/Abajo: -10/+10 y Mayús+ AvPág/RePág: +100/-100 archivos",
            "Haut/Bas : -10/+10 et Maj+ PgSuiv/PgPréc : +100/-100 fichiers",
            "Cima/Baixo: -10/+10 e Shift+ PgDn/PgUp: +100/-100 arquivos",
            "أعلى/أسفل: ‎-10/+10‎ وShift+ PgDn/PgUp: ‎+100/-100‎ ملف",
            "ऊपर/नीचे: -10/+10 और Shift+ PgDn/PgUp: +100/-100 फ़ाइलें",
            "উপর/নিচ: -10/+10 এবং Shift+ PgDn/PgUp: +100/-100 ফাইল",
            "اوپر/نیچے: ‎-10/+10‎ اور Shift+ PgDn/PgUp: ‎+100/-100‎ فائلیں",
            "上/下：-10/+10；Shift+ PgDn/PgUp：+100/-100 个文件")
        Add("Y- случайно, S- слайдшоу, I- случайное слайдшоу. ",
            "Y- random, S- slide, I- random slide. ",
            "Y- випадково, S- слайд-шоу, I- випадкове слайд-шоу. ",
            "Y- zufällig, S- Diashow, I- zufällige Diashow. ",
            "Y- casuale, S- presentazione, I- presentazione casuale. ",
            "Y- aleatorio, S- pase, I- pase aleatorio. ",
            "Y- aléatoire, S- diaporama, I- diaporama aléatoire. ",
            "Y- aleatório, S- apresentação, I- apresentação aleatória. ",
            "Y- عشوائي، S- عرض شرائح، I- عرض شرائح عشوائي. ",
            "Y- यादृच्छिक, S- स्लाइडशो, I- यादृच्छिक स्लाइडशो। ",
            "Y- এলোমেলো, S- স্লাইডশো, I- এলোমেলো স্লাইডশো। ",
            "Y- بے ترتیب، S- سلائیڈ شو، I- بے ترتیب سلائیڈ شو۔ ",
            "Y- 随机，S- 幻灯片，I- 随机幻灯片。 ")
        Add("R/Shift+R для поворота картинки, если фотограф держал камеру боком (T тоже, пока не включён OCR-перевод). ",
            "R/Shift+R to rotate the image, for when the photographer held the camera sideways (T too, unless OCR translation is on). ",
            "R/Shift+R для повороту зображення, якщо фотограф тримав камеру боком (T теж, доки не ввімкнено OCR-переклад). ",
            "R/Umschalt+R dreht das Bild, falls der Fotograf die Kamera quer hielt (T ebenso, solange die OCR-Übersetzung aus ist). ",
            "R/Maiusc+R ruota l'immagine, per quando il fotografo teneva la fotocamera di traverso (anche T, finché la traduzione OCR è disattivata). ",
            "R/Mayús+R gira la imagen, para cuando el fotógrafo sostuvo la cámara de lado (T también, mientras la traducción OCR esté desactivada). ",
            "R/Maj+R fait pivoter l'image, quand le photographe tenait l'appareil de travers (T aussi, tant que la traduction OCR est désactivée). ",
            "R/Shift+R gira a imagem, para quando o fotógrafo segurou a câmera de lado (T também, enquanto a tradução OCR estiver desligada). ",
            "‏R/Shift+R لتدوير الصورة إذا أمسك المصوّر الكاميرا بشكل جانبي (وT أيضًا، ما دامت ترجمة OCR معطّلة). ",
            "R/Shift+R छवि घुमाने के लिए, जब फ़ोटोग्राफ़र ने कैमरा तिरछा पकड़ा हो (T भी, जब तक OCR अनुवाद बंद है)। ",
            "R/Shift+R ছবি ঘোরাতে, যখন ফটোগ্রাফার ক্যামেরা কাত করে ধরেছিলেন (T-ও, যতক্ষণ OCR অনুবাদ বন্ধ)। ",
            "‏R/Shift+R تصویر گھمانے کے لیے، جب فوٹوگرافر نے کیمرہ ترچھا پکڑا ہو (T بھی، جب تک OCR ترجمہ بند ہے)۔ ",
            "R/Shift+R 旋转图片 - 拍照时相机拿歪了就用它（T 也可以，只要 OCR 翻译没开启）。 ")

        ' --- first-run help, after the zoom block ---------------------------------
        Add("F3 для просмотра панели изображений папки. ",
            "F3 to see the panel of folder's images. ", "F3 для перегляду панелі зображень теки. ",
            "F3 zeigt die Bildleiste des Ordners. ", "F3 mostra il pannello delle immagini della cartella. ",
            "F3 muestra el panel de imágenes de la carpeta. ", "F3 affiche le panneau d'images du dossier. ",
            "F3 mostra o painel de imagens da pasta. ", "‏F3 لعرض لوحة صور المجلد. ",
            "F3 फ़ोल्डर की छवि पैनल देखने के लिए। ", "F3 ফোল্ডারের ছবির প্যানেল দেখতে। ",
            "‏F3 فولڈر کا تصویری پینل دیکھنے کے لیے۔ ", "F3 查看文件夹的图片面板。 ")
        Add("F6 для переименования файла. ",
            "F6 to rename the file. ", "F6 для перейменування файлу. ", "F6 benennt die Datei um. ",
            "F6 rinomina il file. ", "F6 cambia el nombre del archivo. ", "F6 renomme le fichier. ",
            "F6 renomeia o arquivo. ", "‏F6 لإعادة تسمية الملف. ", "F6 फ़ाइल का नाम बदलने के लिए। ",
            "F6 ফাইলের নাম বদলাতে। ", "‏F6 فائل کا نام بدلنے کے لیے۔ ", "F6 重命名文件。 ")
        Add("Или раскидайте файлы по папкам клавишами (1,2,3.. - 0) - по одному нажатию на файл. ",
            "Or move/copy files into dest folders by keys (1,2.. - 0) - one keypress per file. ",
            "Або розкидайте файли по теках клавішами (1,2,3.. - 0) - по одному натисканню на файл. ",
            "Oder verteilen Sie Dateien mit den Tasten (1,2,3.. - 0) auf Ordner - ein Tastendruck pro Datei. ",
            "Oppure smista i file nelle cartelle con i tasti (1,2,3.. - 0) - una pressione per file. ",
            "O reparta los archivos por carpetas con las teclas (1,2,3.. - 0): una pulsación por archivo. ",
            "Ou répartissez les fichiers dans les dossiers avec les touches (1,2,3.. - 0) - une frappe par fichier. ",
            "Ou distribua os arquivos pelas pastas com as teclas (1,2,3.. - 0) - uma tecla por arquivo. ",
            "أو وزّع الملفات على المجلدات بالمفاتيح (1,2,3.. - 0) - ضغطة واحدة لكل ملف. ",
            "या कुंजियों (1,2,3.. - 0) से फ़ाइलें फ़ोल्डरों में बाँटें - प्रति फ़ाइल एक बार दबाएँ। ",
            "অথবা কী (1,2,3.. - 0) দিয়ে ফাইল ফোল্ডারে ভাগ করুন - প্রতি ফাইলে একবার চাপ। ",
            "یا کلیدوں (1,2,3.. - 0) سے فائلیں فولڈرز میں بانٹیں - فی فائل ایک دبانا۔ ",
            "或者用按键（1,2,3.. - 0）把文件分到各文件夹 - 每个文件按一下。 ")
        Add("Или удалите текущий файл (del), если он того заслужил. ",
            "Or delete files (del key), if they had it coming. ",
            "Або видаліть поточний файл (del), якщо він на це заслужив. ",
            "Oder löschen Sie die aktuelle Datei (Entf), wenn sie es verdient hat. ",
            "Oppure elimina il file corrente (Canc), se se l'è meritato. ",
            "O elimine el archivo actual (Supr), si se lo ha ganado. ",
            "Ou supprimez le fichier courant (Suppr), s'il l'a bien cherché. ",
            "Ou exclua o arquivo atual (Del), se ele mereceu. ",
            "أو احذف الملف الحالي (Del) إن كان يستحق ذلك. ",
            "या मौजूदा फ़ाइल हटाएँ (Del), अगर वह इसी लायक है। ",
            "অথবা বর্তমান ফাইল মুছুন (Del), যদি সে তার যোগ্য হয়। ",
            "یا موجودہ فائل حذف کریں (Del)، اگر وہ اسی لائق ہے۔ ",
            "或者删除当前文件（Del）- 如果它活该。 ")
        Add("Окно таблицы можно закрепить и щёлкать мышью по колонке с цифрой. ",
            "You can pin the folders-table window and click on the key numbers. ",
            "Вікно таблиці можна закріпити й клацати мишею по колонці з цифрою. ",
            "Das Tabellenfenster lässt sich anheften; dann klicken Sie einfach auf die Zahlenspalte. ",
            "La finestra della tabella si può fissare e poi basta cliccare sulla colonna dei numeri. ",
            "Puede fijar la ventana de la tabla y hacer clic en la columna de números. ",
            "Vous pouvez épingler la fenêtre du tableau et cliquer sur la colonne des chiffres. ",
            "Você pode fixar a janela da tabela e clicar na coluna dos números. ",
            "يمكن تثبيت نافذة الجدول والنقر على عمود الأرقام. ",
            "तालिका विंडो को पिन कर संख्या वाले कॉलम पर क्लिक कर सकते हैं। ",
            "টেবিল উইন্ডো পিন করে সংখ্যার কলামে ক্লিক করতে পারেন। ",
            "ٹیبل ونڈو کو پن کر کے نمبروں والے کالم پر کلک کر سکتے ہیں۔ ",
            "可以固定表格窗口，然后直接点击数字列。 ")
        Add("(U) - вернуть последний перенесённый файл (на случай, если рука дрогнула). ",
            "(U)ndo the last move (for when your hand slipped). ",
            "(U) - повернути останній перенесений файл (на випадок, якщо рука здригнулася). ",
            "(U) macht das letzte Verschieben rückgängig (falls die Hand gezuckt hat). ",
            "(U) annulla l'ultimo spostamento (nel caso ti sia tremata la mano). ",
            "(U) deshace el último movimiento (por si le tembló la mano). ",
            "(U) annule le dernier déplacement (au cas où la main aurait tremblé). ",
            "(U) desfaz a última movimentação (caso a mão tenha tremido). ",
            "‏(U) للتراجع عن آخر نقل (إن ارتجفت يدك). ",
            "(U) अंतिम स्थानांतरण पूर्ववत करें (अगर हाथ हिल गया हो)। ",
            "(U) শেষ সরানো ফিরিয়ে আনুন (হাত কেঁপে গেলে)। ",
            "‏(U) آخری منتقلی واپس کریں (اگر ہاتھ کانپ گیا ہو)۔ ",
            "(U) 撤销上一次移动（万一手抖了）。 ")
        Add(" Щёлкните на этот текст (F1), чтобы он деликатно исчез.",
            " Click on this text (F1) to make it tactfully disappear.",
            " Клацніть на цей текст (F1), щоб він делікатно зник.",
            " Klicken Sie auf diesen Text (F1), damit er taktvoll verschwindet.",
            " Fai clic su questo testo (F1) perché sparisca con discrezione.",
            " Haga clic en este texto (F1) para que desaparezca con discreción.",
            " Cliquez sur ce texte (F1) pour qu'il disparaisse discrètement.",
            " Clique neste texto (F1) para que ele suma discretamente.",
            " انقر على هذا النص (F1) ليختفي بلباقة.",
            " इस पाठ पर क्लिक करें (F1) ताकि यह शालीनता से गायब हो जाए।",
            " এই লেখায় ক্লিক করুন (F1), যেন এটি ভদ্রভাবে মিলিয়ে যায়।",
            " اس متن پر کلک کریں (F1) تاکہ یہ شائستگی سے غائب ہو جائے۔",
            " 点击这段文字（F1），它就会体面地消失。")

        ' --- mainline-only help block (registered in both builds) -----------------
        Add("Shift + цифра верхнего ряда - скопировать файл в ту же папку, куда цифра его переносит. ",
            "Shift + a top-row digit copies the file into the same folder the digit moves it to. ",
            "Shift + цифра верхнього ряду - скопіювати файл до тієї ж теки, куди цифра його переносить. ",
            "Shift + Zifferntaste der oberen Reihe kopiert die Datei in denselben Ordner, in den die Ziffer sie verschiebt. ",
            "Shift + una cifra della fila superiore copia il file nella stessa cartella in cui la cifra lo sposta. ",
            "Shift + un dígito de la fila superior copia el archivo a la misma carpeta a la que el dígito lo mueve. ",
            "Shift + un chiffre de la rangée du haut copie le fichier dans le dossier où le chiffre le déplace. ",
            "Shift + um dígito da fila de cima copia o arquivo para a mesma pasta em que o dígito o move. ",
            "Shift + رقم من الصف العلوي ينسخ الملف إلى المجلد نفسه الذي ينقله إليه الرقم. ",
            "Shift + ऊपरी पंक्ति का अंक फ़ाइल को उसी फ़ोल्डर में कॉपी करता है जहाँ अंक उसे ले जाता है। ",
            "Shift + উপরের সারির অঙ্ক ফাইলটিকে সেই ফোল্ডারেই কপি করে যেখানে অঙ্কটি তাকে সরায়। ",
            "Shift + اوپری قطار کا ہندسہ فائل کو اسی فولڈر میں نقل کرتا ہے جہاں ہندسہ اسے منتقل کرتا ہے۔ ",
            "Shift + 主键盘数字会把文件复制到该数字移动它的那个文件夹。 ")

        ' --- zoom block (modern build only, but registered in both) ---------------
        Add("Масштаб: серый + и - (от курсора), серый / - вписать, серый * - 100 %; колесо можно переключить на масштаб в настройках. ",
            "Zoom: grey + and - (at the cursor), grey / to fit, grey * for 100 %; the wheel can be switched to zoom in Settings. ",
            "Масштаб: сірі + і - (від курсора), сірий / - вписати, сірий * - 100 %; колесо можна перемкнути на масштаб у налаштуваннях. ",
            "Zoom: graues + und - (am Cursor), graues / passt ein, graues * gibt 100 %; das Rad lässt sich in den Einstellungen auf Zoom umstellen. ",
            "Zoom: + e - grigi (al cursore), / grigio adatta, * grigio dà 100 %; la rotella si può impostare sullo zoom nelle impostazioni. ",
            "Zoom: + y - grises (en el cursor), / gris ajusta, * gris da 100 %; la rueda puede cambiarse a zoom en la configuración. ",
            "Zoom : + et - gris (au curseur), / gris ajuste, * gris donne 100 % ; la molette peut être basculée sur le zoom dans les paramètres. ",
            "Zoom: + e - cinza (no cursor), / cinza ajusta, * cinza dá 100 %; a roda pode ser trocada para zoom nas configurações. ",
            "التكبير: ‎+‎ و‎-‎ الرماديان (عند المؤشر)، ‎/‎ الرمادي للملاءمة، ‎*‎ الرمادي لـ100 %؛ ويمكن تحويل العجلة إلى تكبير من الإعدادات. ",
            "ज़ूम: ग्रे + और - (कर्सर पर), ग्रे / फ़िट, ग्रे * 100 %; सेटिंग्स में पहिये को ज़ूम पर बदला जा सकता है। ",
            "জুম: ধূসর + ও - (কার্সরে), ধূসর / ফিট, ধূসর * 100 %; সেটিংসে চাকাকে জুমে বদলানো যায়। ",
            "زوم: سرمئی ‎+‎ اور ‎-‎ (کرسر پر)، سرمئی ‎/‎ فٹ، سرمئی ‎*‎ 100 %؛ ترتیبات میں پہیے کو زوم پر بدلا جا سکتا ہے۔ ",
            "缩放：小键盘 + 和 -（在光标处），/ 适应窗口，* 为 100 %；可在设置中把滚轮切换为缩放。 ")
        Add("Средняя кнопка мыши по картинке - меню со всеми действиями над ней (поворот, масштаб, переименовать, переместить, удалить). ",
            "The middle mouse button on a picture opens a menu with everything you can do to it (rotate, zoom, rename, move, delete). ",
            "Середня кнопка миші по зображенню - меню з усіма діями над ним (поворот, масштаб, перейменувати, перемістити, видалити). ",
            "Die mittlere Maustaste auf einem Bild öffnet ein Menü mit allem, was man damit tun kann (drehen, zoomen, umbenennen, verschieben, löschen). ",
            "Il tasto centrale del mouse su un'immagine apre un menu con tutto ciò che puoi farci (ruota, zoom, rinomina, sposta, elimina). ",
            "El botón central del ratón sobre una imagen abre un menú con todo lo que puede hacerle (girar, zoom, renombrar, mover, eliminar). ",
            "Le bouton du milieu sur une image ouvre un menu avec tout ce qu'on peut en faire (pivoter, zoomer, renommer, déplacer, supprimer). ",
            "O botão do meio do mouse sobre a imagem abre um menu com tudo o que dá para fazer (girar, zoom, renomear, mover, excluir). ",
            "زر الفأرة الأوسط على الصورة يفتح قائمة بكل ما يمكن فعله بها (تدوير، تكبير، إعادة تسمية، نقل، حذف). ",
            "छवि पर माउस का मध्य बटन एक मेन्यू खोलता है जिसमें उससे जुड़े सभी काम हैं (घुमाना, ज़ूम, नाम बदलना, ले जाना, हटाना)। ",
            "ছবির উপর মাউসের মধ্য বোতাম একটি মেনু খোলে যেখানে সব কাজ আছে (ঘোরানো, জুম, নাম বদল, সরানো, মোছা)। ",
            "تصویر پر ماؤس کا درمیانی بٹن ایک مینو کھولتا ہے جس میں تمام کام ہیں (گھمانا، زوم، نام بدلنا، منتقل کرنا، حذف کرنا)۔ ",
            "在图片上按鼠标中键会打开菜单，包含对它的所有操作（旋转、缩放、重命名、移动、删除）。 ")
        Add("У видео: клик по картинке - пауза/продолжить, правая кнопка - меню со всеми действиями над видео. ",
            "For video: a click on the picture pauses/resumes, right-click opens a menu with everything you can do to it. ",
            "У відео: клік по зображенню - пауза/продовжити, права кнопка - меню з усіма діями над відео. ",
            "Bei Video: ein Klick aufs Bild pausiert/setzt fort, Rechtsklick öffnet ein Menü mit allen Aktionen. ",
            "Per il video: un clic sull'immagine mette in pausa/riprende, il tasto destro apre un menu con tutte le azioni. ",
            "En vídeo: un clic en la imagen pausa o reanuda, el clic derecho abre un menú con todas las acciones. ",
            "Pour la vidéo : un clic sur l'image met en pause/reprend, le clic droit ouvre un menu avec toutes les actions. ",
            "No vídeo: um clique na imagem pausa/continua, o botão direito abre um menu com todas as ações. ",
            "في الفيديو: النقر على الصورة يوقف/يستأنف، والزر الأيمن يفتح قائمة بكل الإجراءات. ",
            "वीडियो में: छवि पर क्लिक रोकता/जारी रखता है, दायाँ क्लिक सभी क्रियाओं का मेन्यू खोलता है। ",
            "ভিডিওতে: ছবিতে ক্লিক থামায়/চালায়, ডান ক্লিক সব কাজের মেনু খোলে। ",
            "ویڈیو میں: تصویر پر کلک روکتا/جاری رکھتا ہے، دایاں کلک تمام کاموں کا مینو کھولتا ہے۔ ",
            "视频：点击画面暂停/继续，右键打开包含所有视频操作的菜单。 ")
        Add("A - следующая звуковая дорожка, V - следующие субтитры (и кнопка ""Дорожки"", когда есть из чего выбрать). ",
            "A - next audio track, V - next subtitles (and a ""Tracks"" button when there is a choice). ",
            "A - наступна звукова доріжка, V - наступні субтитри (і кнопка ""Доріжки"", коли є з чого вибрати). ",
            "A - nächste Tonspur, V - nächste Untertitel (und eine Schaltfläche ""Spuren"", wenn es eine Auswahl gibt). ",
            "A - traccia audio successiva, V - sottotitoli successivi (e un pulsante ""Tracce"" quando c'è scelta). ",
            "A: siguiente pista de audio, V: siguientes subtítulos (y un botón ""Pistas"" cuando hay elección). ",
            "A - piste audio suivante, V - sous-titres suivants (et un bouton ""Pistes"" quand il y a le choix). ",
            "A - próxima faixa de áudio, V - próximas legendas (e um botão ""Faixas"" quando há escolha). ",
            "‏A - المسار الصوتي التالي، V - الترجمة التالية (وزر ""المسارات"" عندما يكون هناك خيار). ",
            "A - अगला ऑडियो ट्रैक, V - अगले उपशीर्षक (और विकल्प होने पर ""ट्रैक"" बटन)। ",
            "A - পরবর্তী অডিও ট্র্যাক, V - পরবর্তী সাবটাইটেল (এবং বিকল্প থাকলে ""ট্র্যাক"" বোতাম)। ",
            "‏A - اگلا آڈیو ٹریک، V - اگلے ذیلی عنوانات (اور انتخاب ہونے پر ""ٹریکس"" بٹن)۔ ",
            "A - 下一条音轨，V - 下一条字幕（有可选项时还会出现""轨道""按钮）。 ")
        Add("Это дополнительное окно. Изменения настроек действуют до его закрытия и не сохраняются - настройки хранит первое окно.",
            "This is an additional window. Settings changes apply until it closes and are not saved - the first window owns the settings.", "Це додаткове вікно. Зміни налаштувань діють до його закриття й не зберігаються - налаштування зберігає перше вікно.", "Dies ist ein zusätzliches Fenster. Einstellungsänderungen gelten bis zum Schließen und werden nicht gespeichert - das erste Fenster verwaltet die Einstellungen.", "Questa è una finestra aggiuntiva. Le modifiche alle impostazioni valgono fino alla chiusura e non vengono salvate: le impostazioni sono gestite dalla prima finestra.", "Esta es una ventana adicional. Los cambios de configuración se aplican hasta que se cierre y no se guardan: la primera ventana conserva la configuración.", "Ceci est une fenêtre supplémentaire. Les modifications de réglages s'appliquent jusqu'à sa fermeture et ne sont pas enregistrées : la première fenêtre conserve les réglages.", "Esta é uma janela adicional. As alterações de configuração valem até ela ser fechada e não são salvas: a primeira janela mantém as configurações.", "هذه نافذة إضافية. تسري تغييرات الإعدادات حتى إغلاقها ولا تُحفظ - النافذة الأولى تحتفظ بالإعدادات.", "यह एक अतिरिक्त विंडो है। सेटिंग बदलाव इसके बंद होने तक लागू रहते हैं और सहेजे नहीं जाते - सेटिंग पहली विंडो रखती है।", "এটি একটি অতিরিক্ত উইন্ডো। সেটিংস পরিবর্তন বন্ধ হওয়া পর্যন্ত কার্যকর থাকে এবং সংরক্ষিত হয় না - প্রথম উইন্ডো সেটিংস রাখে।", "یہ ایک اضافی ونڈو ہے۔ ترتیبات میں تبدیلیاں بند ہونے تک لاگو رہتی ہیں اور محفوظ نہیں ہوتیں - ترتیبات پہلی ونڈو رکھتی ہے۔", "这是一个附加窗口。设置更改仅在它关闭前有效，不会保存；设置由第一个窗口保存。")
        Add("дополнительное окно", "additional window", "додаткове вікно", "zusätzliches Fenster", "finestra aggiuntiva", "ventana adicional", "fenêtre supplémentaire", "janela adicional", "نافذة إضافية", "अतिरिक्त विंडो", "অতিরিক্ত উইন্ডো", "اضافی ونڈو", "附加窗口")
    End Sub

End Class
