Option Strict On

' <summary>
' Captions of the classic settings window: title, grid headers, the five tab
' headers, group boxes and every checkbox/label. These used to be one 85-line
' If Is_Russian_Language Then .. Else .. End If block; now they are one set of
' assignments and one table.
'
' Note "Настройки" and a few short words are registered in other tables already -
' the dictionary would just keep the last one, so only the keys unique to this
' window live here.
' </summary>
Partial Public NotInheritable Class Localization

    Private Shared Sub AddSettingsChromeStrings()

        Add("клавиша", "KEY", "клавіша", "Taste", "tasto", "tecla", "touche", "tecla", "المفتاح", "कुंजी", "কী", "کلید", "按键")
        Add("каталог-получатель", "destination folder", "тека-отримувач", "Zielordner", "cartella di destinazione", "carpeta de destino", "dossier de destination", "pasta de destino", "مجلد الوجهة", "गंतव्य फ़ोल्डर", "গন্তব্য ফোল্ডার", "منزل فولڈر", "目标文件夹")

        ' tab headers
        Add("Каталоги-получатели", "Destination folders", "Теки-отримувачі", "Zielordner", "Cartelle di destinazione", "Carpetas de destino", "Dossiers de destination", "Pastas de destino", "مجلدات الوجهة", "गंतव्य फ़ोल्डर", "গন্তব্য ফোল্ডার", "منزل فولڈرز", "目标文件夹")
        Add("Просмотр", "Viewing", "Перегляд", "Ansicht", "Visualizzazione", "Visualización", "Affichage", "Visualização", "العرض", "देखना", "দেখা", "دیکھنا", "浏览")
        Add("Видео и качество", "Video and quality", "Відео та якість", "Video und Qualität", "Video e qualità", "Vídeo y calidad", "Vidéo et qualité", "Vídeo e qualidade", "الفيديو والجودة", "वीडियो और गुणवत्ता", "ভিডিও ও মান", "ویڈیو اور معیار", "视频与画质")
        Add("Файлы и система", "Files and system", "Файли та система", "Dateien und System", "File e sistema", "Archivos y sistema", "Fichiers et système", "Arquivos e sistema", "الملفات والنظام", "फ़ाइलें और सिस्टम", "ফাইল ও সিস্টেম", "فائلیں اور سسٹم", "文件与系统")
        Add("OCR и перевод", "OCR & translation", "OCR і переклад", "OCR und Übersetzung", "OCR e traduzione", "OCR y traducción", "OCR et traduction", "OCR e tradução", "OCR والترجمة", "OCR और अनुवाद", "OCR ও অনুবাদ", "OCR اور ترجمہ", "OCR 与翻译")

        ' group boxes
        Add("Фон", "Background", "Фон", "Hintergrund", "Sfondo", "Fondo", "Arrière-plan", "Fundo", "الخلفية", "पृष्ठभूमि", "পটভূমি", "پس منظر", "背景")
        Add("Информация на экране", "On-screen info", "Інформація на екрані", "Bildschirminfos", "Info a schermo", "Información en pantalla", "Infos à l'écran", "Informações na tela", "معلومات على الشاشة", "स्क्रीन पर जानकारी", "পর্দায় তথ্য", "اسکرین پر معلومات", "屏幕信息")
        Add("Слайдшоу", "Slideshow", "Слайд-шоу", "Diashow", "Presentazione", "Pase de diapositivas", "Diaporama", "Apresentação de slides", "عرض الشرائح", "स्लाइडशो", "স্লাইডশো", "سلائیڈ شو", "幻灯片")
        Add("Панель миниатюр", "Thumbnail panel", "Панель мініатюр", "Miniaturansicht", "Pannello miniature", "Panel de miniaturas", "Panneau de miniatures", "Painel de miniaturas", "لوحة المصغّرات", "थंबनेल पैनल", "থাম্বনেইল প্যানেল", "تھمب نیل پینل", "缩略图面板")
        Add("Качество изображения", "Image quality", "Якість зображення", "Bildqualität", "Qualità immagine", "Calidad de imagen", "Qualité d'image", "Qualidade da imagem", "جودة الصورة", "छवि गुणवत्ता", "ছবির মান", "تصویر کا معیار", "图像质量")
        Add("Видео", "Video", "Відео", "Video", "Video", "Vídeo", "Vidéo", "Vídeo", "الفيديو", "वीडियो", "ভিডিও", "ویڈیو", "视频")
        Add("Операции с файлами", "File operations", "Операції з файлами", "Dateivorgänge", "Operazioni sui file", "Operaciones de archivo", "Opérations sur les fichiers", "Operações de arquivo", "عمليات الملفات", "फ़ाइल कार्य", "ফাইল অপারেশন", "فائل کے عمل", "文件操作")
        Add("Ассоциации и интеграция", "Associations and integration", "Асоціації та інтеграція", "Verknüpfungen und Integration", "Associazioni e integrazione", "Asociaciones e integración", "Associations et intégration", "Associações e integração", "الاقترانات والتكامل", "संबद्धताएँ और एकीकरण", "সংযুক্তি ও সমন্বয়", "ایسوسی ایشنز اور انضمام", "关联与集成")
        Add("Язык", "Language", "Мова", "Sprache", "Lingua", "Idioma", "Langue", "Idioma", "اللغة", "भाषा", "ভাষা", "زبان", "语言")

        ' labels and checkboxes
        Add("Цвет фона:", "Background color:", "Колір фону:", "Hintergrundfarbe:", "Colore di sfondo:", "Color de fondo:", "Couleur de fond :", "Cor de fundo:", "لون الخلفية:", "पृष्ठभूमि रंग:", "পটভূমির রঙ:", "پس منظر کا رنگ:", "背景颜色：")
        Add("Показывать размер изображений", "Show picture sizes", "Показувати розмір зображень", "Bildgrößen anzeigen", "Mostra le dimensioni delle immagini", "Mostrar el tamaño de las imágenes", "Afficher la taille des images", "Mostrar o tamanho das imagens", "إظهار أحجام الصور", "छवियों का आकार दिखाएँ", "ছবির আকার দেখান", "تصاویر کا سائز دکھائیں", "显示图片尺寸")
        Add("Показывать размер файлов", "Show file sizes", "Показувати розмір файлів", "Dateigrößen anzeigen", "Mostra le dimensioni dei file", "Mostrar el tamaño de los archivos", "Afficher la taille des fichiers", "Mostrar o tamanho dos arquivos", "إظهار أحجام الملفات", "फ़ाइलों का आकार दिखाएँ", "ফাইলের আকার দেখান", "فائلوں کا سائز دکھائیں", "显示文件大小")
        Add("Показывать дату и время файла", "Show file datetime", "Показувати дату й час файлу", "Datum und Uhrzeit der Datei anzeigen", "Mostra data e ora del file", "Mostrar la fecha y hora del archivo", "Afficher la date et l'heure du fichier", "Mostrar a data e hora do arquivo", "إظهار تاريخ ووقت الملف", "फ़ाइल की तिथि और समय दिखाएँ", "ফাইলের তারিখ ও সময় দেখান", "فائل کی تاریخ اور وقت دکھائیں", "显示文件日期时间")
        Add("Имя файла и позиция поверх изображения", "File name and position over the image", "Ім'я файлу та позиція поверх зображення", "Dateiname und Position über dem Bild", "Nome file e posizione sopra l'immagine", "Nombre y posición del archivo sobre la imagen", "Nom du fichier et position sur l'image", "Nome do arquivo e posição sobre a imagem", "اسم الملف وموضعه فوق الصورة", "छवि पर फ़ाइल का नाम और स्थिति", "ছবির উপরে ফাইলের নাম ও অবস্থান", "تصویر پر فائل کا نام اور مقام", "在图片上显示文件名和位置")
        Add("Колесо мыши приближает (иначе листает)", "Mouse wheel zooms (otherwise it flips files)", "Колесо миші наближає (інакше гортає)", "Mausrad zoomt (sonst blättert es)", "La rotella ingrandisce (altrimenti sfoglia)", "La rueda amplía (si no, pasa archivos)", "La molette zoome (sinon elle fait défiler)", "A roda amplia (senão troca de arquivo)", "عجلة الفأرة تكبّر (وإلا تتنقل)", "माउस व्हील ज़ूम करता है (वरना फ़ाइल बदलता है)", "মাউস হুইল জুম করে (নাহলে ফাইল পাল্টায়)", "ماؤس وہیل زوم کرتا ہے (ورنہ فائل بدلتا ہے)", "滚轮缩放（否则翻页）")
        Add("Авто-поворот по EXIF", "Auto-rotate by EXIF", "Автоповорот за EXIF", "Automatisch nach EXIF drehen", "Rotazione automatica da EXIF", "Rotación automática por EXIF", "Rotation automatique selon EXIF", "Girar automaticamente pelo EXIF", "تدوير تلقائي حسب EXIF", "EXIF से स्वतः घुमाव", "EXIF অনুযায়ী স্বয়ংক্রিয় ঘূর্ণন", "EXIF کے مطابق خودکار گھماؤ", "按 EXIF 自动旋转")
        Add("Демонстрировать видео зациклено", "Loop video playback", "Демонструвати відео зациклено", "Video in Schleife abspielen", "Riproduci il video in loop", "Reproducir el vídeo en bucle", "Lire la vidéo en boucle", "Reproduzir o vídeo em loop", "تشغيل الفيديو بشكل متكرر", "वीडियो लूप में चलाएँ", "ভিডিও লুপে চালান", "ویڈیو لوپ میں چلائیں", "循环播放视频")
        Add("Без звука по умолчанию", "Muted by default", "Без звуку за замовчуванням", "Standardmäßig stumm", "Silenziato per impostazione predefinita", "Silenciado de forma predeterminada", "Muet par défaut", "Sem som por padrão", "صامت افتراضيًا", "डिफ़ॉल्ट रूप से मौन", "ডিফল্টে নিঃশব্দ", "ڈیفالٹ میں خاموش", "默认静音")
        Add("Громкость по умолчанию (%):", "Default volume (%):", "Гучність за замовчуванням (%):", "Standardlautstärke (%):", "Volume predefinito (%):", "Volumen predeterminado (%):", "Volume par défaut (%) :", "Volume padrão (%):", "مستوى الصوت الافتراضي (%):", "डिफ़ॉल्ट ध्वनि (%):", "ডিফল্ট ভলিউম (%):", "ڈیفالٹ آواز (%):", "默认音量（%）：")
        Add("Интервал слайдшоу (с):", "Slideshow interval (s):", "Інтервал слайд-шоу (с):", "Diashow-Intervall (s):", "Intervallo presentazione (s):", "Intervalo del pase (s):", "Intervalle du diaporama (s) :", "Intervalo da apresentação (s):", "فاصل عرض الشرائح (ث):", "स्लाइडशो अंतराल (से):", "স্লাইডশোর বিরতি (সে):", "سلائیڈ شو کا وقفہ (س):", "幻灯片间隔（秒）：")
        Add("Размер карточки панели:", "Panel card size:", "Розмір картки панелі:", "Größe der Panel-Karte:", "Dimensione scheda pannello:", "Tamaño de tarjeta del panel:", "Taille de la vignette :", "Tamanho do cartão do painel:", "حجم بطاقة اللوحة:", "पैनल कार्ड का आकार:", "প্যানেল কার্ডের আকার:", "پینل کارڈ کا سائز:", "面板卡片大小：")
        Add("Режим копирования файлов (не перенос)", "COPY mode (files are not moving)", "Режим копіювання файлів (не перенесення)", "Kopiermodus (Dateien werden nicht verschoben)", "Modalità copia (i file non vengono spostati)", "Modo copiar (los archivos no se mueven)", "Mode copie (les fichiers ne sont pas déplacés)", "Modo cópia (os arquivos não são movidos)", "وضع النسخ (لا تُنقل الملفات)", "कॉपी मोड (फ़ाइलें स्थानांतरित नहीं होतीं)", "কপি মোড (ফাইল সরে না)", "کاپی موڈ (فائلیں منتقل نہیں ہوتیں)", "复制模式（文件不移动）")
        Add("Использовать независимые потоки для операций с файлами", "Use independent thread for operations with files", "Використовувати незалежні потоки для операцій з файлами", "Eigenen Thread für Dateivorgänge verwenden", "Usa un thread indipendente per le operazioni sui file", "Usar un hilo independiente para las operaciones de archivo", "Utiliser un thread distinct pour les opérations sur les fichiers", "Usar thread independente para operações de arquivo", "استخدام مسار مستقل لعمليات الملفات", "फ़ाइल कार्यों के लिए स्वतंत्र थ्रेड", "ফাইল অপারেশনের জন্য আলাদা থ্রেড", "فائل کے عمل کے لیے الگ تھریڈ", "文件操作使用独立线程")
        Add("Не запрашивать подтверждение перед операцией с файлом", "No request before file operation", "Не запитувати підтвердження перед операцією з файлом", "Vor Dateivorgängen nicht nachfragen", "Nessuna conferma prima delle operazioni sui file", "No pedir confirmación antes de una operación de archivo", "Pas de confirmation avant une opération sur les fichiers", "Sem confirmação antes de uma operação de arquivo", "بلا تأكيد قبل عمليات الملفات", "फ़ाइल कार्य से पहले पुष्टि न माँगें", "ফাইল অপারেশনের আগে নিশ্চিতকরণ নয়", "فائل کے عمل سے پہلے تصدیق نہیں", "文件操作前不再确认")
        Add("Зарегистрировать как программу просмотра изображений по умолчанию", "Register as default image viewer", "Зареєструвати як програму перегляду зображень за замовчуванням", "Als Standard-Bildbetrachter registrieren", "Registra come visualizzatore immagini predefinito", "Registrar como visor de imágenes predeterminado", "Définir comme visionneuse d'images par défaut", "Registrar como visualizador de imagens padrão", "التسجيل كعارض صور افتراضي", "डिफ़ॉल्ट छवि दर्शक के रूप में पंजीकृत करें", "ডিফল্ট ছবি দর্শক হিসেবে নিবন্ধন", "ڈیفالٹ تصویر ویور کے طور پر رجسٹر کریں", "注册为默认图片查看器")
        Add("Зарегистрировать как видеопроигрыватель по умолчанию", "Register as default video player", "Зареєструвати як відеопрогравач за замовчуванням", "Als Standard-Videoplayer registrieren", "Registra come lettore video predefinito", "Registrar como reproductor de vídeo predeterminado", "Définir comme lecteur vidéo par défaut", "Registrar como player de vídeo padrão", "التسجيل كمشغّل فيديو افتراضي", "डिफ़ॉल्ट वीडियो प्लेयर के रूप में पंजीकृत करें", "ডিফল্ট ভিডিও প্লেয়ার হিসেবে নিবন্ধন", "ڈیفالٹ ویڈیو پلیئر کے طور پر رجسٹر کریں", "注册为默认视频播放器")
        Add("Показывать таблицу получателей поверх медиафайла", "Show recipients table over the media file", "Показувати таблицю отримувачів поверх медіафайлу", "Zieltabelle über der Mediendatei anzeigen", "Mostra la tabella delle destinazioni sopra il file", "Mostrar la tabla de destinos sobre el archivo", "Afficher la table des destinations sur le média", "Mostrar a tabela de destinos sobre o arquivo", "إظهار جدول الوجهات فوق ملف الوسائط", "मीडिया फ़ाइल पर गंतव्य तालिका दिखाएँ", "মিডিয়া ফাইলের উপরে গন্তব্য টেবিল দেখান", "میڈیا فائل پر منزل ٹیبل دکھائیں", "在媒体文件上显示目标表格")

        Add("Укажите каталог переноса/копирования для клавиши {0}", "Select dest folder for key {0}", "Вкажіть теку перенесення/копіювання для клавіші {0}", "Ziel- bzw. Kopierordner für Taste {0} wählen", "Scegli la cartella di destinazione per il tasto {0}", "Elija la carpeta de destino para la tecla {0}", "Choisissez le dossier de destination pour la touche {0}", "Escolha a pasta de destino para a tecla {0}", "اختر مجلد الوجهة للمفتاح {0}", "कुंजी {0} के लिए गंतव्य फ़ोल्डर चुनें", "{0} কী-এর জন্য গন্তব্য ফোল্ডার নির্বাচন করুন", "کلید {0} کے لیے منزل فولڈر منتخب کریں", "为按键 {0} 选择目标文件夹")
    End Sub

End Class
